### ISSUE TITLE
Unable to migrate after manual DDL

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#2356] opened 2021-03-12 12:19 UTC
- EdgeDB Version: `1.0-beta.2+dev.5519.ga407daf8b`

Steps to Reproduce:

```edgeql
edgedb> select count(schema::Migration);
{11}
edgedb> create type a; drop type a;
OK: CREATE TYPE
OK: DROP TYPE
edgedb> select count(schema::Migration);
{13}
edgedb> select schema::Migration { name };
{
  schema::Migration {name: 'm1s4ux2ifvuqj6lilfn7fvnpjo2axgze7ebrlbvvjoh5nzs7zafeeq'},
  schema::Migration {name: 'm1bwwtn5kb7iuojymql2ej6kny73r6uhdgq24ezmawbgintz4nvc3q'},
  schema::Migration {name: 'm1tqngnmntnyrlpqst6ski3qlwy344wm4xba4vnvjaptfhb5lgfb4a'},
  schema::Migration {name: 'm1modjnhnkp7wjmipxlj4ahvq2gbocp7o74auzgm4ol655tx776vva'},
  schema::Migration {name: 'm1qechmup7a6kbed6dlg2ece5r5xtknrmrnzh2uuuoy2gkzfk4c3uq'},
  schema::Migration {name: 'm1bdoan5tmad3acvxjrrltgg5hfrc35nqchqn3gxif3zcvkupnld6a'},
  schema::Migration {name: 'm1drl2hwprxndex6mbjfm3zcn2bsbod5kl63byhsqtwpk3ztyxdi3a'},
  schema::Migration {name: 'm1ssa5af5w2tlcibwpwjrnowf3g7rzvs3d7kezbzbasyu3rnnq6l2q'},
  schema::Migration {name: 'm1jzjprzcy37mqjanabobtx5urcpl6glhk6adkiz5thzz5r7irvzwa'},
  schema::Migration {name: 'm1khqhcrvtliasbc552xkzcte7wdr6s4ntlp2goqsfllq5wvl6l6qa'},
  schema::Migration {name: 'm1t37bozs75tyvufmu3npfrg5sq52fxs47fm2pyquxctja3jn3f2za'},
  schema::Migration {name: 'm1jvzns3ucokjugdievkmihsczc24x5ivkorkpokjgv2lcwxq4sqwq'},
  schema::Migration {name: 'm1caxnitfxa6fwyexhrb6gq5uxly2kq3aqztaoal6rdj32dz3eg6pa'},
}
```
Every time you modify schema database creates migration and migration name is different even if you revert your changes (compare last entries), isn't name supposed to be hash of current schema and be the same if you revert changes?

After doing these manual changes I can't migrate:
```bash
$ edgedb migrate
edgedb error: There is no database revision m1caxnitfxa6fwyexhrb6gq5uxly2kq3aqztaoal6rdj32dz3eg6pa in the filesystem. Consider updating sources.
```
If I try to change migration name in file I get another error:
```bash
$ edgedb migrate
edgedb error: could not read migrations in ./dbschema/migrations: could not read migration file ./dbschema/migrations/00003.edgeql: migration name should be `m1tqngnmntnyrlpqst6ski3qlwy344wm4xba4vnvjaptfhb5lgfb4a` but `m1caxnitfxa6fwyexhrb6gq5uxly2kq3aqztaoal6rdj32dz3eg6pa` is used instead.
Migration names are computed from the hash of the migration contents. To proceed you must fix the statement to read as:
  CREATE MIGRATION m1tqngnmntnyrlpqst6ski3qlwy344wm4xba4vnvjaptfhb5lgfb4a ONTO ...
if this migration is not applied to any database. Alternatively, revert the changes to the file.
```

Is it a bug that migration name is different even if schema is the same? If no, how do I fix my migration workflow?

**Comment by elprans** [comment] 2021-03-12 17:24
This is by design.  Migrations in EdgeDB act like git commits, i.e they form a linear chain.  Manual DDL is also treated as a micro-migration, otherwise a migration-oriented workflow would be totally broken by a spurious DDL command somewhere, since the migration system would not be able to properly reconcile your on-disk migration history with that of the database.

Right now, there is no equivalent to `git reset` or `git rebase --autosquash`, although those are on the TODO list.

> If no, how do I fix my migration workflow?

It's best to avoid mixing pure DDL with migrations.

To fix your instance you need to copy the additional migrations from the database into files in `dbschema/migrations`.

This query should help:

```
SELECT schema::Migration { name, parent := (SELECT  .parents.name LIMIT 1), script };
```

@tailhook, we need a CLI command to do this automatically.

**Comment by Fogapod** [comment] 2021-03-15 18:18
Thanks, this works, but in my case adding these migrations is not the best solution `git reset` alternative would be better because I don't want to pollute migration history in my git repository. I had to reset database.

Maybe there could be some fool-proof switch that does not let you run DDL code outside migrations and is on by default? This would be a breaking change though. If not in database itself, maybe in CLI? If the switch is on and you try to run DDL it will print a warning suggesting to use migration workflow instead and showing how to flip the switch if you really need DDL (this will be annoying, maybe only print warning 1 time per REPL session)

**Comment by msullivan** [comment] 2022-02-10 22:37
We have that switch now; is this fixed?

**Comment by elprans** [comment] 2022-02-10 23:31
Yeah, let's close this, but let's also open a new issue for a CLI command to re-read the migrations out of the database.

**Closed** 2022-09-27 17:42 UTC
