### ISSUE TITLE
Migration including exclusive constraint on computed property fails with "InternalServerError: dangling scope pointer to node"

### ISSUE THREAD

**Issue by CodesInChaos** [edgedb/edgedb#1720] opened 2020-08-28 16:41 UTC
Run the following migration on alpha 5 on ubuntu 20:

```
START MIGRATION TO {
module default {
	abstract type Named {
		required property name -> str;

		property canonical_name := (str_lower(.name));
		
		delegated constraint exclusive on (__subject__.canonical_name);
	}
}
};
POPULATE MIGRATION;
COMMIT MIGRATION;
```
Fails with the following error:
```
ERROR: InternalServerError: dangling scope pointer to node with uid:3 in <ir.Set 'ns~1@@(__derived__::expr~4)' at 0x7fc357ab2a60>
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1795, in compile_eql_tokens
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1429, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1352, in _compile_dispatch_ql
          return self._compile_ql_migration(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 789, in _compile_ql_migration
          target_schema = s_ddl.apply_sdl(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/ddl.py", line 364, in apply_sdl
          target_schema = delta.apply(target_schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/delta.py", line 1094, in apply
          schema = objop.apply(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/delta.py", line 2471, in apply
          schema = self._alter_innards(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/delta.py", line 2434, in _alter_innards
          schema = op.apply(schema, context=context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/delta.py", line 2033, in apply
          schema = self._create_begin(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/constraints.py", line 722, in _create_begin
          self._populate_concrete_constraint_attrs(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/constraints.py", line 829, in _populate_concrete_constraint_attrs
          final_expr = s_expr.Expression.compiled(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/schema/expr.py", line 156, in compiled
          ir = qlcompiler.compile_ast_to_ir(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/__init__.py", line 175, in wrapper
          return func(*args, **kwargs)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/__init__.py", line 224, in compile_ast_to_ir
          ir_expr = stmtctx_mod.fini_expression(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/stmtctx.py", line 116, in fini_expression
          cb(ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/stmtctx.py", line 748, in _enforce_singleton
          enforce_singleton_now(irexpr, singletons=singletons, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/stmtctx.py", line 710, in enforce_singleton_now
          scope = pathctx.get_set_scope(ir_set=irexpr, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha5/lib/python3.8/site-packages/edb/edgeql/compiler/pathctx.py", line 127, in get_set_scope
          raise errors.InternalServerError(
      edb.errors.InternalServerError: dangling scope pointer to node with uid:3 in <ir.Set 'ns~1@@(__derived__::expr~4)' at 0x7fc357ab2a60>

```

**Comment by elprans** [comment] 2020-08-28 16:44
Dupe of #1622?

**Comment by CodesInChaos** [comment] 2020-08-28 16:54
The linked issue was a feature request to support the same constraint syntax on computed properties, which normal properties already support (attempting it gives a syntax error).

Here I tried to use the object level constraint syntax, referencing a computed property as part of an expression, which resulted in an internal server error.

So they're strictly speaking two separate issues. But if you want to fix them together, you can combine them.

**Comment by msullivan** [comment] 2021-01-26 21:21
This seems fixed. Not sure when.

**Closed by msullivan** 2021-01-26 21:21 UTC
