### ISSUE TITLE
Can't create type and a function that references it at the same time

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#1891] opened 2020-10-16 22:40 UTC
```
CREATE MIGRATION {
    CREATE TYPE default::Note {
        CREATE REQUIRED SINGLE PROPERTY note -> std::str;
    };
    CREATE FUNCTION default::foo(x: default::Note) -> std::str USING (SELECT
        (x.note ++ "!")
    );
};
```
fails with `edb.errors.InternalServerError: relation "edgedb_9b4cb2b5-0f4e-11eb-8480-7de12ecda434.c1149538-0fff-11eb-a12b-0fcdfa949b6c_t" does not exist`.

(I wrote this as `CREATE MIGRATION` to show that the problem isn't how we compute migrations but creating the type and the function at the same time.)

The issue is that the function refers to the inheritance view for Note, not the underlying table, and inheritance views are always created at the end of the script. So even though the creation of Note is done first, the inheritance view isn't so the function creation failed.

**Comment by elprans** [comment] 2020-10-16 22:42
Seems to be a dupe of #1625?

**Closed** 2020-10-16 23:00 UTC
