### ISSUE TITLE
Filter and ordering does not work on calculated properties with group by

### ISSUE THREAD

**Issue by TheHyphen** [edgedb/edgedb#4257] opened 2022-08-14 18:38 UTC
- EdgeDB Version: 2.1+c73716f
- OS Version: WSL 2

Steps to Reproduce:

Run this query in the EdgeDB UI:
```
with
  M := (select Shipments),
  groups := (
    group M
    using
     grouping := .client.name
    by grouping
  ) 
select groups {
  name := .key.grouping,
  value := count(.elements)
} filter .value > 30
```
throws an error:
> InternalServerError: Can't find materialized set ns~24@ns~25@@(__derived__::groups@w~2).>elements[IS default::Shipments]

But if I change the filter to 
```
filter count(.elements) > 30
```
then, it works as expected.

Schema:
```
module default {
    type Client {
        required property name -> str;
        property email -> str;
    }
    type Shipments {
        required link client -> Client;
        required property date -> cal::local_datetime;
    }
}
```

**Comment by msullivan** [comment] 2022-10-18 20:31
Oh, duplicate of #4240

**Closed by msullivan** 2022-10-18 20:31 UTC
Labels: bug, compiler
