### ISSUE TITLE
error on alter module name {} back to module default {}

### ISSUE THREAD

**Issue by mazeForGit** [edgedb/edgedb#4995] opened 2023-02-08 11:58 UTC
- EdgeDB Version: "edgedb --version"
EdgeDB CLI 2.2.6+af56767
- EdgeDB CLI Version: "select sys::get_version_as_str()"
"2.9+b1d697b"
- OS Version: Windows 10

Steps to Reproduce:

1. modify default.esdl

```
module cm {
    type Requirement {
		property name -> str;
		multi link parentOf -> Requirement;
		multi link testedBy -> Test;
	}	  
	type Test {
		property name -> str;
	}  
}
```
2. apply changes
3. modify default.esdl : module cm --> module default

```
module default {
    type Requirement {
		property name -> str;
		multi link parentOf -> Requirement;
		multi link testedBy -> Test;
	}	  
	type Test {
		property name -> str;
	}  	
}
```

4. apply changes

edgedb migration create
```
Connecting to an EdgeDB instance at localhost:10700...
edgedb error: InternalServerError: dependency cycle between ('alter', 'cm::Requirement') and ('rename', 'cm::__|testBy@cm|Requirement')
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 185, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2333, in compile_in_tx
          return self._compile(ctx=ctx, source=source), ctx.state
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1804, in _compile
          return self._try_compile(ctx=ctx, source=original)
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1871, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1729, in _compile_dispatch_ql
          query = self._compile_ql_migration(
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1216, in _compile_ql_migration
          guided_diff = s_ddl.delta_schemas(
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/schema/ddl.py", line 337, in delta_schemas
          objects = s_ordering.linearize_delta(
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/schema/ordering.py", line 113, in linearize_delta
          sortedlist = [i[1] for i in topological.sort_ex(depgraph)]
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/common/topological.py", line 187, in sort_ex
          visit(key)
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/common/topological.py", line 170, in visit
          visit(n, weak_link=weak_link)
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/common/topological.py", line 170, in visit
          visit(n, weak_link=weak_link)
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/common/topological.py", line 170, in visit
          visit(n, weak_link=weak_link)
        [Previous line repeated 1 more time]
        File "/home/edgedb/.local/share/edgedb/portable/2.9/lib/python3.10/site-packages/edb/common/topological.py", line 149, in visit
          raise CycleError(
      edb.common.topological.CycleError: dependency cycle between ('alter', 'cm::Requirement') and ('rename', 'cm::__|testBy@cm|Requirement')
```

**Comment by msullivan** [comment] 2023-02-10 01:17
I was not able to reproduce this issue on either 2.9 or on master.

Can you confirm that you got this error with *exactly* these schema files, with nothing else in them?

**Comment by mazeForGit** [comment] 2023-02-10 13:57
Hi. It was exactly this configuration. I would like to give it another try as soon I can.

**Comment by msullivan** [comment] 2023-02-10 14:51
The error message seems to mention a `testBy` element that doesn't appear in this one

**Comment by mazeForGit** [comment] 2023-02-10 15:26
Hi Michael,

Now I had some time to do the same again on two new installations and was also not able to reproduce it.
It is fine with me if the issue is marked as not reproducible and closed.

By the way:
Is there any way to address some questions on installing and troubleshooting?
I’m not able to setup to listen to an ip-address instead of localhost.
I can’t write query at REPL using Safari.
etc.
..

**Comment by msullivan** [comment] 2023-02-10 16:26
Please file separate issues for those questions
(I'm not the right person for those and the people who are won't be looking at this bug)

**Comment by msullivan** [comment] 2023-02-10 16:26
There does seem like there is a real bug here but without a way to reproduce, so I'm closing

**Closed by msullivan** 2023-02-10 16:26 UTC
Labels: bug, migrations, need info, compiler
