### ISSUE TITLE
Use of __subject__@target is broken in link constraints

### ISSUE THREAD

**Issue by adriangb** [edgedb/edgedb#2095] opened 2021-01-02 00:57 UTC
Coming from https://github.com/edgedb/edgedb/discussions/1714#discussioncomment-58644.

Tested via Docker  `nightly`/`1.0-alpha.8+dev.5305.gfddd6f37`

A minimal reproducible example on a clean slate DB:
```
START MIGRATION TO {
    module default {
        type TypeOne {};
        type TypeTwo {
            multi link linkup -> TypeOne {
                constraint exclusive on ((__subject__@target,));
            };
        }
    }
};
POPULATE MIGRATION;
COMMIT MIGRATION;
```

Fails on `POPULATE MIGRATION`:

<details><summary>Traceback</summary>

```
ERROR: InternalServerError: 'PointerRef' object has no attribute 'is_scalar'
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 86, in compile_ir_to_sql_tree
          qtree = dispatch.compile(ir_expr, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 56, in compile_Set
          return _compile_set_in_singleton_mode(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 642, in _compile_set_in_singleton_mode
          return dispatch.compile(node.expr, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/stmt.py", line 43, in compile_SelectStmt
          return dispatch.compile(stmt.result, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 56, in compile_Set
          return _compile_set_in_singleton_mode(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 642, in _compile_set_in_singleton_mode
          return dispatch.compile(node.expr, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 515, in compile_Tuple
          val = dispatch.compile(e.val, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/functools.py", line 875, in wrapper
          return dispatch(args[0].__class__)(*args, **kw)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 56, in compile_Set
          return _compile_set_in_singleton_mode(ir_set, ctx=ctx)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/expr.py", line 661, in _compile_set_in_singleton_mode
          ptr_stor_info = pg_types.get_ptrref_storage_info(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/types.py", line 430, in get_ptrref_storage_info
          if irtyputils.is_scalar(source):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/ir/typeutils.py", line 55, in is_scalar
          return typeref.is_scalar
      AttributeError: 'PointerRef' object has no attribute 'is_scalar'
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1915, in compile_in_tx
          return self._compile(ctx=ctx, source=source)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1442, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1496, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1389, in _compile_dispatch_ql
          query = self._compile_ql_migration(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 1100, in _compile_ql_migration
          ddl_query = self._compile_and_apply_ddl_stmt(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 784, in _compile_and_apply_ddl_stmt
          block, new_types = self._process_delta(ctx, delta)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/server/compiler/compiler.py", line 419, in _process_delta
          schema = delta.apply(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/delta.py", line 3978, in apply
          schema = sd.DeltaRoot.apply(self, schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/schema/delta.py", line 1254, in apply
          schema = objop.apply(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/delta.py", line 188, in apply
          schema = self.__class__.get_adaptee().apply(self, schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/schema/delta.py", line 2588, in apply
          schema = self._create_innards(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/schema/delta.py", line 2557, in _create_innards
          schema = op.apply(schema, context=context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/delta.py", line 1957, in apply
          schema = s_objtypes.AlterObjectType.apply(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/schema/delta.py", line 3067, in apply
          schema = self._alter_innards(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/schema/delta.py", line 3030, in _alter_innards
          schema = op.apply(schema, context=context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/delta.py", line 2576, in apply
          schema = s_links.AlterLink.apply(self, schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/schema/delta.py", line 3067, in apply
          schema = self._alter_innards(schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/schema/delta.py", line 3030, in _alter_innards
          schema = op.apply(schema, context=context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/delta.py", line 1100, in apply
          bconstr = schemac_to_backendc(subject, constraint, schema, context)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/schemamech.py", line 311, in schema_constraint_to_backend_constraint
          exprdata = cls._edgeql_ref_to_pg_constr(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/schemamech.py", line 141, in _edgeql_ref_to_pg_constr
          sql_tree = compiler.compile_ir_to_sql_tree(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha8-dev5305/lib/python3.8/site-packages/edb/pgsql/compiler/__init__.py", line 93, in compile_ir_to_sql_tree
          raise errors.InternalServerError(*args) from e
      edb.errors.InternalServerError: 'PointerRef' object has no attribute 'is_scalar'
```

</details>

Using `constraint exclusive on ((__subject__@source, ))` works.

And just to make sure I'm understanding correctly, using `constraint exclusive` is equivalent to `constraint exclusive on ((__subject__@source, __subject__@target ))`?

**Comment by elprans** [comment] 2021-01-02 01:45
Duplicate of #1786

**Comment by adriangb** [comment] 2021-01-02 01:48
Ah sorry for the duplicate! Bad searching on my part. Please feel free to close this.

**Closed** 2021-02-08 21:39 UTC
