### ISSUE TITLE
Creating an index on an abstract type doesn't create it on types that extend it

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#3599] opened 2022-03-10 08:33 UTC
- EdgeDB Version: EdgeDB 1.0+9236fa8
- OS Version: Mac OS monterey

Steps to Reproduce:

```
abstract type WithPgId {
  required property pg_id -> str {
    constraint exclusive;
  };
  index on (.pg_id);
}

type User extending WithPgId{
  property name -> str;
}
```
2. Fill the user type with 1 million rows and try a select query
3. Add an index to the `pg_id` on the User type --> the query is now fast

**Comment by msullivan** [comment] 2022-03-10 21:59
I'm not able to reproduce this. When I try this, we do create an index on `WithPgId`. We actually create an index even without the `index` declaration, because of the `exclusive` constraint on `pg_id`.

When I tried this, I could verify that the query plan was doing a sequential scan, and that querying by `pg_id` was much faster than by `name`.

I'm not sure what issue you were hitting--the first run of a query is usually much slower, since we need to run the compiler. Maybe it was that?

**Comment by msullivan** [comment] 2022-03-10 23:21
I'm going to close this issue. Feel free to open up a discussion about the perf issue you are seeing, or to reopen this if you think I'm mistaken about the index issue and have some more detailed reproduction instructions to share?

Thanks!

**Closed by msullivan** 2022-03-10 23:21 UTC

**Comment by haikyuu** [comment] 2022-03-11 14:37
> the first run of a query is usually much slower
I noticed it on the first run. So maybe that's it
