### ISSUE TITLE
ISE when using a WITH-bound GROUP in DML

### ISSUE THREAD

**Issue by alrhalford** [edgedb/edgedb#4536] opened 2022-10-17 15:14 UTC
- EdgeDB Version: `v2.3`
- OS Version: Docker, running on an Arch Linux host (`6.0.2-arch1-1`)

Steps to Reproduce:

Schema:

```
module default {
  abstract type Auditable {
    required property creation_timestamp -> datetime {
      readonly := true;
      default := datetime_current();
    } 
  }
  abstract type Argument {
    required property description -> str;
    required property argument_required -> bool {
      default := false
    }
  }
  type IntegerArgument extending Argument {
    property minimum -> bigint;
    property maximum -> bigint;
  }
  type StringArgument extending Argument {
    property minimum_length -> bigint;
    property maximum_length -> bigint;
  }
  type Func extending Auditable {
    required property description -> str;
    multi link arguments -> Argument {
      constraint exclusive;
      property name -> str;
    }
    property argument_count := count(.arguments)
  }
};
```

Query:

```
WITH
argument_data := <json>$arguments,
items := (SELECT (GROUP item := json_array_unpack(argument_data) USING variant := item["variant"] BY variant)),
integer := (SELECT items FILTER <str>.key.variant = "integer").elements,
inserted := (
  INSERT Func {
    description := <str>$description,
  }
),
FOR item IN integer UNION (
  UPDATE inserted set {
    arguments += (
      INSERT IntegerArgument {
        @name := <str>item['name'],
        description := <str>item['description'],
        minimum := <int64>item['minimum'],
        maximum := <int64>item['maximum'],
      }
    )
  }
)
```
This results in:

`InternalServerError: Can't find materialized set ns~10@@(__derived__::items@w~2)`

Notes:
This query probably looks a bit odd, since it's a minimum reproducible example. In the full query there are multiple argument types, each with a WITH clause and each with a FOR loop to insert them into the polymorphic `arguments` property.

**Comment by alexhalford** [comment] 2022-10-18 11:01
@elprans If it helps, I've managed to reproduce the bug without the initial `INSERT Func`, so just:
```
WITH
argument_data := <json>$arguments,
items := (SELECT (GROUP item := json_array_unpack(argument_data) USING variant := item["variant"] BY variant)),
integer := (SELECT items FILTER <str>.key.variant = "integer").elements,
FOR item IN integer UNION (
      INSERT IntegerArgument {
        description := <str>item['description'],
      }
)

```
So it looks as though it's just the looped INSERT that gives the error.

I also tried re-querying rather than using the context:

```
WITH
argument_data := <json>$arguments,
items := (SELECT (GROUP item := json_array_unpack(argument_data) USING variant := item["variant"] BY variant)),
integer := (SELECT items FILTER <str>.key.variant = "integer").elements,
inserted := (
  INSERT Func {
    description := <str>$description,
  }
),
FOR item IN integer UNION (
  WITH inserted_arg := (
      INSERT IntegerArgument {
        description := <str>item['description'],
      }
    ),
    name := <str>item["name"]
    UPDATE Func FILTER .id = <uuid>inserted.id SET {
        arguments += ( SELECT IntegerArgument{@name := name} FILTER .id = <uuid>inserted_arg.id)
    }
)
```
This _does not error_, but it does not insert the `IntegerArgument`, and (obviously), the `Func` object does not have any elements in its `arguments` block.

But, just to make things super weird, if I do this:

```
WITH
argument_data := <json>$arguments,
items := (SELECT (GROUP item := json_array_unpack(argument_data) USING variant := item["variant"] BY variant)),
integer := (SELECT items FILTER <str>.key.variant = "integer").elements,
FOR item IN integer UNION (
  WITH inserted_arg := (
      INSERT IntegerArgument {
        description := <str>item['description'],
      }
    ),
    SELECT inserted_arg
)
```
The `IntegerArgument` _does_ get inserted.

But, last one, if I do this:

```
WITH
argument_data := <json>$arguments,
items := (SELECT (GROUP item := json_array_unpack(argument_data) USING variant := item["variant"] BY variant)),
integer := (SELECT items FILTER <str>.key.variant = "integer").elements,
FOR item IN integer UNION (
  WITH inserted_arg := (
      INSERT IntegerArgument {
        description := <str>item['description'],
      }
    ),
    SELECT IntegerArgument FILTER .id = <uuid>inserted_arg.id
)
```
the query returns nothing, but _does_ successfully insert the IntegerArgument object.

So, I guess the WITH is not binding the `inserted_arg` (and possibly also the `inserted`) variables properly?

I hope the above helps, let me know if there is anything I can do to help debug :)

**Comment by msullivan** [comment] 2022-10-18 18:06
The core bug is probably related to `GROUP`; there is a collection of similar GROUP bugs that I'm working on.

**Comment by msullivan** [comment] 2022-10-18 18:08
All of the other query results are correct: a newly inserted object isn't available to be selected or updated from the database during the same query.

**Comment by msullivan** [comment] 2022-10-18 21:41
Inlining `items` into `integer` works around the issue

**Comment by msullivan** [comment] 2022-10-18 21:49
```
WITH
argument_data := <json>$arguments,
items := ((GROUP item := json_array_unpack(argument_data) USING variant := item["variant"] BY variant)),
FOR item IN items.elements UNION (
      INSERT IntegerArgument {
        description := <str>item['description'],
      }
);
```
is a slight more minimized version
Also
```
WITH
argument_data := <json>$arguments,
items := ((GROUP item := json_array_unpack(argument_data) USING variant  := item["variant"] BY variant)),
INSERT X {
   strs := <str>items.elements['description'],
};
```
where X has a multi property strs.

Also, this variant doesn't use `GROUP` but probably shares the same materialization related root cause:
```
WITH                                                                     
items := (for x in {'foo', 'bar'} union ({ multi elements := x }))       
INSERT X {                                                               
   strs := <str>items.elements,                                          
};
```

**Comment by alexhalford** [comment] 2022-10-19 00:14
Sorry if I'm being stupid, but how would this apply to multiple argument types? I need to be able to insert each type separately, e.g:

```
WITH
argument_data := <json>$arguments,
items := (SELECT (GROUP item := json_array_unpack(argument_data) USING variant := item["variant"] BY variant)),
integer := (SELECT items FILTER <str>.key.variant = "integer").elements,
boolean := (SELECT items FILTER <str>.key.variant = "boolean").elements,
inserted := (
  INSERT Func {
    description := <str>$description,
  }
),
FOR item IN integer UNION (
  UPDATE inserted set {
    arguments += (
      INSERT IntegerArgument {
        @name := <str>item['name'],
        description := <str>item['description'],
        minimum := <int64>item['minimum'],
        maximum := <int64>item['maximum'],
      }
    )
  }
)
FOR item IN boolean UNION (
  UPDATE inserted set {
    arguments += (
      INSERT BooleanArgument {
        @name := <str>item['name'],
        ... some other set of fields
      }
    )
  }
)
```

**Comment by msullivan** [comment] 2022-10-19 20:04
Sorry, I mostly left notes for myself without being particularly helpful to you.

You are running into a couple of problems. First, you have hit a bug in the interaction of `GROUP` and `INSERT`/`UPDATE`, where depending on this group in your UPDATEs is triggering an internal compiler error. This can be easily worked around, because using `GROUP` here is probably an unnecessary complication anyway, and you can just filter (I switched from BooleanArgument to StringArgument because that is what you used in your example schema).
```
items := json_array_unpack(argument_data),
integer := (SELECT items FILTER <str>items['variant'] = "integer"),
string := (SELECT items FILTER <str>items['variant'] = "string"),
```
This should work around the GROUP bug.

The second problem you have is that we do not support inserting and updating an object in the same query. You need to include everything you want in the INSERT itself.

Unfortunately doing this is complicated by limitations in support for link properties (see #4436).

Looking at your schema and query, it seems to me that `name` doesn't need to be a link property, and would probably be better off being a property of `Argument` instead. (The `arguments` link has an exclusive constraint anyway.) If you have `name` a property on `Argument`, then the query you want looks like:
```
WITH
argument_data := <json>$arguments,
items := json_array_unpack(argument_data),
integer := (SELECT items FILTER <str>items['variant'] = "integer"),
string := (SELECT items FILTER <str>items['variant'] = "string"),
INSERT Func {
  description := <str>$description,
  arguments := {
   (FOR item IN integer UNION (
     INSERT IntegerArgument {
       name := <str>item['name'],
       description := <str>item['description'],
       minimum := <int64>item['minimum'],
       maximum := <int64>item['maximum'],
     }
   )),
   (FOR item IN string UNION (
     INSERT StringArgument {
       name := <str>item['name'],
       description := <str>item['description'],
     }
   ))
  }
};
```

**Comment by alexhalford** [comment] 2022-10-20 20:14
You're absolutely right, that is much clearer. Thank you for your help!

**Comment by msullivan** [comment] 2023-07-11 00:29
I'm closing this in favor of https://github.com/edgedb/edgedb/issues/5312, which is a duplicate of this with a somewhat cleaner comment section

**Closed by msullivan** 2023-07-11 00:29 UTC
Labels: bug, compiler
