### ISSUE TITLE
Cryptic uuid error message when function created that matches on parameter with union type operator

### ISSUE THREAD

**Issue by Dhghomon** [edgedb/edgedb#6069] opened 2023-09-15 03:08 UTC
- EdgeDB Version: 3.3+7771468
- EdgeDB CLI Version: 3.5.0+40f966d
- OS Version: Windows 11

Steps to Reproduce:

1. Create the following schema:

```
module default {
  type Wizard;
  type Warrior;
  type Barbarian;

  type PlayerCharacter {
    required game_character: Wizard | Warrior | Barbarian;
  }

  function pc_message(character: PlayerCharacter) -> str using (
    "It's a Wizard!" if character.game_character is Wizard else 
    "It's a Warrior!" if character.game_character is Warrior else
    "It's a Barbarian!"
  );
}
```

2. Try to apply migration, get the following message:

``` 
edgedb error: InternalServerError: syntax error at or near "uuid"
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: syntax error at or near "uuid"
```

Interestingly, migrating without the function and then copying and pasting its function body separately in a query does work:

```
edgedb> insert Wizard;

edgedb> insert PlayerCharacter {
....... game_character := assert_single((select Wizard))
....... };

edgedb> with character := PlayerCharacter,
....... select "It's a Wizard!" if character.game_character is Wizard else
.......     "It's a Warrior!" if character.game_character is Warrior else
.......     "It's a Barbarian!";
{'It\'s a Wizard!'}
```

And I don't see anything particularly weird in the DDL statements for the function:

```
CREATE FUNCTION default::pc_message(character: default::PlayerCharacter) ->  std::str USING (("It's a Wizard!" IF (character.game_character IS default::Wizard) ELSE ("It's a Warrior!" IF (character.game_character IS default::Warrior) ELSE "It's a Barbarian!")));
```

**Comment by freeatnet** [comment] 2023-09-16 15:50
Hey @Dhghomon! Fellow edgedb user here.

`character` is one of the user-defined function argument names that cause an error (see https://github.com/edgedb/edgedb/issues/6062). You might be able to work around the issue by renaming the argument to something else.

**Comment by Dhghomon** [comment] 2023-09-18 23:56
@freeatnet Fascinating! Changing the argument name does indeed solve the problem so looks like it's the same issue.

**Comment by msullivan** [comment] 2023-09-22 21:41
Yeah, dupe of #6062, fix pending

**Closed by msullivan** 2023-09-22 21:41 UTC
