### ISSUE TITLE
Auth don't work with CLI

### ISSUE THREAD

**Issue by notramo** [edgedb/edgedb#6516] opened 2023-11-26 20:30 UTC
Despite having set the global token, can't use built-in auth from CLI.

### Steps to reproduce
Enter into EdgeDB CLI:
```
edgedb> set global ext::auth::client_token := 'your valid JWT token here';
OK: SET GLOBAL
edgedb> select ext::auth::ClientTokenIdentity;
edgedb error: QueryAssertionError: JWT signature mismatch
```

Note that the **exact same** token perfectly works when used with the TypeScript client. I also checked it with a JWT signature checking tool, and the signature is correct.

**Comment by scotttrinh** [comment] 2023-12-13 21:56
Cannot reproduce on latest 4.2 build:

```
EdgeDB 4.2+833dd8d (repl 3.5.0-dev)
Type \help for help, \quit to quit.
edgedb> set global ext::auth::client_token := "<redacted>";
OK: SET GLOBAL
edgedb> select global ext::auth::ClientTokenIdentity;
{
  ext::auth::Identity {
    id: be59fdca-95f8-11ee-8563-5fc8be373a61,
  },
}
```

Can you double check that the token is the exact same as what you have in the TypeScript client global and ensure that you haven't rotated the auth signing key since creating the token?

**Comment by msullivan** [comment] 2023-12-18 19:06
I'm going to close this, since we haven't been able to reproduce it at all; if you still can, feel free to reopen

**Closed by msullivan** 2023-12-18 19:06 UTC
Labels: need info
