### ISSUE TITLE
Branches with the GitHub and Vercel integrations failing when there's a forward slash

### ISSUE THREAD

**Issue by nathanburgess** [edgedb/edgedb#7358] opened 2024-05-16 22:01 UTC
- EdgeDB Version: 5.2+1e07d04
- EdgeDB CLI Version: 5.1.0+8ff9f85
- OS Version: Sonoma 14.5 (23F79)

Steps to Reproduce:

1. Set up the GitHub and Vercel integrations with EdgeDB Cloud
2. Create a branch with a forward slash in the name like `feat/some-feature-name`
3. Push up a PR so the integrations run
4. Try to click the branch name on cloud.edgedb.com
5. There should be an error page saying the database doesn't exist

![EdgeDB Cloud-Arc@2x](https://github.com/edgedb/edgedb/assets/12576267/7da2df8a-171c-4b51-b90d-2ad0600a8fd3)

![EdgeDB Cloud-Arc@2x](https://github.com/edgedb/edgedb/assets/12576267/b523378e-22d3-4b01-a5c6-a3424da92a18)

**Comment by jaclarke** [comment] 2024-05-17 10:17
Duplicate of https://github.com/edgedb/edgedb-ui/issues/352

**Closed** 2024-05-17 14:34 UTC
