### ISSUE TITLE
Sporadic connection issues on creation and restore of a new database

### ISSUE THREAD

**Issue by bradsbrown** [edgedb/edgedb#4692] opened 2022-11-18 16:19 UTC
- EdgeDB Version: 2.6
- OS Version: (official EdgeDB Docker Image, running in AWS ECS  container)

Steps to Reproduce:

1. have 2 EdgeDB ECS Fargate container services running, pointing to the same RDS postgres backend, with an existing "main" database
2. create a new test env DB (`edgedb database create {new db}`)
3. pull a db dump from the main db and restore it to the new db (`edgedb --dsn "{dsn}/{main db}" dump db.dump && edgdb --dsn "{dsn}/{new db}" restore db.dump`)
4. run a migration to make sure any new migrations in the test env code are laid on top of the existing restore schema (`edgedb migration apply`)

Expected: The new test database is now fully set up, with the full data and schema from the main db along with any new migrations in the test code

Actual: sometimes this works just fine. Sometimes I receive one of two errors, with no real consistency I've observed for why it'd be one or the other. From the CLI command, I'll either see a `database '{test db}' does not accept connections` when running the restore *or* the migration... *or* a `specified migration parent does not exist` when running the migration (which would suggest to me that the restore didn't fully succeed).

Additional notes:
* Checking the EdgeDB service logs, the `does not accept connections` error on the CLI correlates to this in the service logs (db name replaced for obscurity purposes):
```
| 1668786725456 | ---- Exception occurred: database '{name of database}' does not accept connections ----                                    |
| 1668786725456 | 1. edb.errors.AccessError: database '{name of database}' does not accept connections                                       |
| 1668786725456 | ---- Traceback ----                                                                                                        |
| 1668786725456 |     edb/server/protocol/binary.pyx, line 1310, in edb.server.protocol.binary.EdgeConnection.main                           |
| 1668786725456 |                                                                                                                            |
| 1668786725456 |     edb/server/protocol/binary.pyx, line 476, in auth                                                                      |
| 1668786725456 |                                                                                                                            |
| 1668786725456 | ---- Details ----                                                                                                          |
| 1668786725456 | edb.errors.AccessError: database '{name of database}' does not accept connections                                          |
| 1668786725456 | ERROR 7 2022-11-18T15:52:05.455 asyncio: unhandled error in edgedb protocol while accepting new connection                 |
| 1668786725456 | protocol: <edb.server.protocol.binary.EdgeConnectionBackwardsCompatible object at 0x7fee39afae60>                          |
| 1668786725456 | task: <Task pending name='Task-583093' coro=<EdgeConnection.main() running> cb=[TaskGroup._on_task_done(), set.discard()]> |
| 1668786725456 | transport: None                                                                                                            |
| 1668786745611 | ---- Exception occurred: database '{name of database}' does not accept connections ----                                    |
| 1668786745611 | 1. edb.errors.AccessError: database '{name of database}' does not accept connections                                       |
| 1668786745611 | ---- Traceback ----                                                                                                        |
| 1668786745611 |     edb/server/protocol/binary.pyx, line 1310, in edb.server.protocol.binary.EdgeConnection.main                           |
| 1668786745611 |                                                                                                                            |
| 1668786745611 |     edb/server/protocol/binary.pyx, line 476, in auth                                                                      |
| 1668786745611 |                                                                                                                            |
| 1668786745611 | ---- Details ----                                                                                                          |
| 1668786745611 | edb.errors.AccessError: database '{name of database}' does not accept connections                                          |
| 1668786745611 | ERROR 7 2022-11-18T15:52:25.611 asyncio: unhandled error in edgedb protocol while accepting new connection                 |
| 1668786745611 | protocol: <edb.server.protocol.binary.EdgeConnectionBackwardsCompatible object at 0x7fee39afae60>                          |
| 1668786745611 | task: <Task pending name='Task-583114' coro=<EdgeConnection.main() running> cb=[TaskGroup._on_task_done(), set.discard()]> |
| 1668786745611 | transport: None                                                                                                            |
```

* Worth noting that the entire create/dump/restore/migrate is handled by a script we built so the timing is pretty rapid between steps. To attempt to combat this, just in case there was a problem of readiness immediately after the `create` or the `restore`, I have added a wait helper that pauses a a minimum of 30 seconds, then attempts a simple `select count(Object)` query against the test DB every 20 seconds until successful, before it allows the script to continue to the next step. So if this is a race condition it's a fairly large one.

**Comment by bradsbrown** [comment] 2023-01-20 17:59
Update: we've bumped to the `edgedb:2.9` image but otherwise nothing has really changed in our workflow. Still seeing this issue.

**Comment by elprans** [comment] 2023-01-20 18:20
Do you mind posting your fargate task definition?

**Comment by bradsbrown** [comment] 2023-01-20 19:21
@elprans I'll provide it to you via the discord shortly...

**Comment by msullivan** [comment] 2023-05-11 18:57
@fantix do you think this is #5463?

**Comment by fantix** [comment] 2023-05-11 19:09
Right, I believe those errors were caused by issues fixed in the following PRs:

`does not accept connections` -> #5032
`specified migration parent does not exist` -> #5463

**Comment by msullivan** [comment] 2023-05-11 19:29
Great!

**Closed by msullivan** 2023-05-11 19:29 UTC
