### ISSUE TITLE
EdgeQL needs a SUBSET operator

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#169] opened 2018-05-04 23:26 UTC
Currently it is fairly non-trivial to check whether one set is a subset of another. We need an operator to make that nice. Additionally, having this operator will allow to make this specific operation more efficient.

Any suggestions for naming?

**Comment by elprans** [comment] 2018-11-05 23:53
Duplicate of #294

**Closed by elprans** 2018-11-05 23:53 UTC
