### ISSUE TITLE
Docker install not working

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#1172] opened 2020-01-31 17:34 UTC
Hello again. I was so thrilled when i saw the launch of the alpha 2. Keep the good work.
❤️ 
Docker install isn't working for me. Here are the details:

- EdgeDB Version: `1.0-alpha.2+g16f75ece5.d20200122`
- OS Version: Mac High Siera 10.13.6
- Docker version 19.03.5, build 633a0ea

Steps to Reproduce:

1. I followed the instructions to install via Docker
```
docker run -it --rm -p 5656:5656 -p 8888:8888 \
            --name=edgedb-server2 \
            -v datadir:/var/lib/edgedb/data \
            edgedb/edgedb
```
The error is the following:

```
INFO 1 2020-01-31 17:28:48,714 edb.server: EdgeDB server (1.0-alpha.2+g16f75ece5.d20200122) starting.
=========================================== Exception occurred: pg_ctl stop exited with status 1: pg_ctl: could not send stop signal (PID: 31): No such process
 ===========================================

2. edb.server.pgcluster.ClusterError: cluster is not running

------------------------------------------------------------------------------------------------ Traceback -------------------------------------------------------------------------------------------------

    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/main.py, line 287, in run_server
        > need_cluster_restart = _init_cluster(cluster, args)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/main.py, line 141, in _init_cluster
        > need_restart = asyncio.run(bootstrap.bootstrap(cluster, bootstrap_args))
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/asyncio/runners.py, line 43, in run
        > return loop.run_until_complete(main)
    uvloop/loop.pyx, line 1456, in uvloop.loop.Loop.run_until_complete

    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/bootstrap.py, line 636, in bootstrap
        > pgconn = await cluster.connect()
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/pgcluster.py, line 82, in connect
        > conn_info = self.get_connection_spec()
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/pgcluster.py, line 119, in get_connection_spec
        > addr = self.get_connection_addr()
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/pgcluster.py, line 104, in get_connection_addr
        > raise ClusterError('cluster is not running')

edb.server.pgcluster.ClusterError: cluster is not running

==================================================================== During handling of the above exception, another exception occurred ====================================================================

1. edb.server.pgcluster.ClusterError: pg_ctl stop exited with status 1: pg_ctl: could not send stop signal (PID: 31): No such process


------------------------------------------------------------------------------------------------ Traceback -------------------------------------------------------------------------------------------------

    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/bin/edgedb-server, line 10, in <module>
        > sys.exit(main())
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/click/core.py, line 722, in __call__
        > return self.main(*args, **kwargs)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/click/core.py, line 697, in main
        > rv = self.invoke(ctx)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/click/core.py, line 895, in invoke
        > return ctx.invoke(self.callback, **ctx.params)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/click/core.py, line 535, in invoke
        > return callback(*args, **kwargs)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/main.py, line 567, in main
        > server_main(**kwargs)
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/main.py, line 559, in server_main
        > run_server(ServerConfig(**kwargs))
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/main.py, line 322, in run_server
        > cluster.stop()
    /usr/lib/x86_64-linux-gnu/edgedb-1-alpha2/lib/python3.8/site-packages/edb/server/pgcluster.py, line 347, in stop
        > raise ClusterError(

edb.server.pgcluster.ClusterError: pg_ctl stop exited with status 1: pg_ctl: could not send stop signal (PID: 31): No such process
```

**Comment by elprans** [comment] 2020-01-31 17:39
Hmm.  Works for me.  Are you trying on a fresh data dir?

**Comment by haikyuu** [comment] 2020-01-31 21:50
Yes indeed

**Comment by elprans** [comment] 2020-02-01 18:18
@1st1 This might be docker-on-macOS related. Please see if you can reproduce.

**Comment by 1st1** [comment] 2020-05-25 19:23
@ambv Can you repro this?

**Comment by ambv** [comment] 2020-05-25 19:30
The nightlies work for me on Catalina. I'm using the Docker images quite frequently actually. Just confirmed it works with a clean environment (besides base Debian being there):
```
$ docker run -it --rm -p 5656:5656 -p 8888:8888 \
            --name=edgedb-server2 \
            -v datadir:/tmp/edgedbdata \
            edgedb/edgedb
Unable to find image 'edgedb/edgedb:latest' locally
latest: Pulling from edgedb/edgedb
804555ee0376: Already exists
0e2ebc6490c9: Pull complete
1d0a147d395e: Pull complete
Digest: sha256:50b5926bc73ade884d280da57db961ea2428cc6f329507bda7248b4fbf77c089
Status: Downloaded newer image for edgedb/edgedb:latest
Bootstrapping EdgeDB instance...
CONFIGURE SYSTEM
CONFIGURE SYSTEM
INFO 1 2020-05-25 19:29:50,989 edb.server: EdgeDB server (1.0-alpha.2+g16f75ece5.d20200122) starting.
INFO 1 2020-05-25 19:29:54,508 edb.server: Serving on 0.0.0.0:5656
INFO 1 2020-05-25 19:29:54,509 edb.server: Serving on /run/edgedb/.s.EDGEDB.5656
INFO 1 2020-05-25 19:29:54,509 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656
```

@haikyuu, do you still see this issue?

**Comment by ambv** [comment] 2020-05-25 19:37
By the way, @haikyuu, prefer stopping the container with `docker stop edgedb-server2` instead of CTRL+C. The latter can cause some spurious exceptions to show up which are otherwise harmless.

**Comment by 1st1** [comment] 2020-05-28 00:12
Going to close this since apparently this works with the latest.

**Closed by 1st1** 2020-05-28 00:12 UTC

**Comment by haikyuu** [comment] 2020-05-28 11:27
It works fine now. Thank you @ambv @1st1

**Comment by haikyuu** [comment] 2020-05-31 12:17
Yes indeed. It works fine now.

Thank you
