### ISSUE TITLE
Support named tuples or dict objects for bulk queries

### ISSUE THREAD

**Issue by thedeadliestcatch** [edgedb/edgedb#6750] opened 2024-01-30 19:11 UTC
Per https://github.com/edgedb/edgedb/discussions/2290:

Currently the bulk query system depends on JSON for complex multi field queries. This is highly impractical for the Python clients, for example.

A typical use-case scenario:

- We have an array or list of dicts whose key names match an object's field names.
- We need to run queries (such as an INSERT or SELECT) for each dict.
- The bulk query functionality needs a JSON text input.
- The dict objects must then be converted to a JSON object, and then to a text representation.

The conversion is then a three (or minimum 2) step process with non-zerocopy operations. Tuples and dicts can use object references more or less interchangeably via the zip() method, for example.

**Comment by 1st1** [comment] 2024-01-30 19:32
What data type do you use as dict keys?

**Comment by msullivan** [comment] 2024-01-30 19:43
I assume the dict keys here are strings?

I'm going to close this as a duplicate of https://github.com/edgedb/edgedb-python/issues/374, but I'll try to get that prioritized higher, since it should be pretty easy

**Closed by msullivan** 2024-01-30 19:43 UTC
