### ISSUE TITLE
Insert fails silently when also updating another object

### ISSUE THREAD

**Issue by jonaird** [edgedb/edgedb#1771] opened 2020-09-14 06:03 UTC
- EdgeDB Version:Alpha 5
- OS Version: OSx 10.15.6

Steps to Reproduce:

The following queries returned the object that should have been updated but failed to insert the new object or update the object. I also don't get any errors:
```
WITH comment := (INSERT Comment{... })
UPDATE Post
FILTER ....
SET {comments+=comment}
```
```
UPDATE Post
FILTER ....
SET {comments+=(INSERT Comment{...})}
```
If I set the variable but don't update the Post object, the insert succeeds:
```
WITH comment := (INSERT Comment{... })
SELECT comment
```
It also works if I split it into two queries
```
INSERT Comment{...};
UPDATE Post
FILTER ....
SET {comments+=(SELECT Comment ....)}
```

Schema:
The relevant parts are:
```
abstract type Content extending Tx {
    required property voteAddress -> str;
    required link user -> User;
    multi link votes -> Vote;
    property voteTotal := sum(.votes.voteAmount);
    multi link comments -> Comment;
    
}

type Post extending Content { 
    required property title -> str;
    required property url -> str;
    property description -> str;
    
}

type Comment extending Content{
    required property body -> str;
    required link rootPost -> Post;
}
```

**Comment by elprans** [comment] 2020-09-14 17:05
I can't seem to reproduce.  Comments are inserted correctly for me.  Can you try the latest nightly?

**Comment by jonaird** [comment] 2020-09-19 06:43
I tried to upgrade to nightly but got this error: 
```
installer: Package name is EdgeDB
installer: Upgrading at base path /
installer: The upgrade was successful.
Error: failed to restore "default": Directory not empty (os error 66)
```
 
If I try it again, I get this:
```
 edgedb server upgrade --to-nightly -v default
[2020-09-19T06:38:29Z INFO  edgedb::server::upgrade] Version nightly is up to date 1.0a6.dev5077+gbc97e3ec-<unknown>, skipping instance: default
``` 
 
But If I check the version of default, it's still at 1-alpha5:
```
edgedb server status --extended
default:
  Status: inactive
  Service file: exists
  Version: 1-alpha5
...
```

```
┌────────────────────────────┬─────────────────────────┬───────────┬─────────────────────────┬────────────────────┐
│       Major Version        │      Full Version       │ Available │        Installed        │       Param        │
│ 1-alpha3                   │ 1.0a3-2020060201        │ package   │                         │ --version=1-alpha3 │
│ 1-alpha4                   │ 1.0a4-2020071614        │ package   │ package:1.0a4-<unknown> │ --version=1-alpha4 │
│ 1-alpha5                   │ 1.0a5-2020082622        │ package   │ package:1.0a5-<unknown> │ --version=1-alpha5 │
│ 1-alpha6 (nightly)         │ 1.0a6.dev5056+g4fb6cf00 │ package   │                         │ --nightly          │
│ 1-alpha6-dev5069 (nightly) │ 1.0a6.dev5069+g0839d6e8 │ package   │                         │ --nightly          │
│ 1-alpha6-dev5071 (nightly) │ 1.0a6.dev5071+g747ee86b │ package   │                         │ --nightly          │
│ 1-alpha6-dev5073 (nightly) │ 1.0a6.dev5073+g7bedf02b │ package   │                         │ --nightly          │
│ 1-alpha6-dev5077 (nightly) │ 1.0a6.dev5077+gbc97e3ec │ package   │ package                 │ --nightly          │
└────────────────────────────┴─────────────────────────┴───────────┴─────────────────────────┴────────────────────┘
```

**Comment by 1st1** [comment] 2021-10-23 00:05
Closing this issue since it looks like we couldn't repro it back than. Feel free to reopen.

**Closed by 1st1** 2021-10-23 00:05 UTC
