### ISSUE TITLE
InternalServerError: more than one row returned by a subquery used as an expression

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb#1170] opened 2020-01-30 20:17 UTC
- EdgeDB Version: 1.0-alpha.2+g16f75ece5.d20200122
- OS Version: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-1051-aws x86_64)

Trying to update a multi link fails if the set returned by a `FOR x IN y UNION ...` expression contains duplicate objects. A workaround trying to add the duplicate objects separately fails with `QueryError: invalid reference to link property in top level shape`, same as in this issue: #904

Steps to Reproduce:
```
CREATE TYPE Person {
  CREATE REQUIRED PROPERTY name -> str;
};

CREATE TYPE Movie {
  CREATE REQUIRED PROPERTY title -> str;
  CREATE MULTI LINK cast -> Person {
    CREATE PROPERTY character -> str;
  };
};

INSERT Person {
  name := 'Actor 1'
};

INSERT Person {
  name := 'Actor 2'
};

INSERT Movie {
  title := 'Movie 1'
};

# This works with different actors
WITH cast := [
  (name := 'Actor 1', character := 'Some Character'),
  (name := 'Actor 2', character := 'Another Character')
]
UPDATE Movie
FILTER .title = 'Movie 1'
SET {
  cast := (
    FOR actor IN {array_unpack(cast)}
    UNION (
      SELECT Person {
        @character := actor.character
      }
      FILTER .name = actor.name
    )
  )
};

# This fails with error:
# InternalServerError: more than one row returned by a subquery used as an expression
WITH cast := [
  (name := 'Actor 1', character := 'Some Character'),
  (name := 'Actor 1', character := 'Another Character')
#               ^ same actor
]
UPDATE Movie
FILTER .title = 'Movie 1'
SET {
  cast := (
    FOR actor IN {array_unpack(cast)}
    UNION (
      SELECT Person {
        @character := actor.character
      }
      FILTER .name = actor.name
    )
  )
};
```

**Comment by jaclarke** [comment] 2020-01-30 20:24
Just to clarify, this error also occurs without the link property, so starting from an empty cast, the following `UPDATE` works the first time, but fails the second time with the InternalServerError
```
UPDATE Movie
FILTER .title = 'Movie 1'
SET {
  cast := .cast UNION (
    SELECT Person FILTER .name = 'Actor 1'
  )
}
```

**Comment by elprans** [comment] 2020-01-30 20:26
ISE confirmed.

>  A workaround trying to add the duplicate objects separately

Linked sets cannot contain duplicate objects in EdgeDB by design, but the handling of the violation here is obviously broken.  If you need to link to the same object twice, you will need to add an indirection via an intermediate object.  It seems like you want to make the same person play different roles, so making `@character` an array, although updating that might be awkward with the currently available syntax.

**Comment by elprans** [comment] 2020-01-30 20:29
> but fails the second time with the InternalServerError

Try putting `DISTINCT ( )` around it as a workaround for now.

**Comment by jaclarke** [comment] 2020-01-30 20:53
Ok, I can just make character an array, it's only some test data I was importing. It might be useful to add a note somewhere in the docs, as I was assuming that multi link sets could contain duplicates from what it says [here](https://edgedb.com/docs/edgeql/overview#everything-is-a-set) that 

> EdgeQL sets are multisets, as they do not require the elements to be unique

**Comment by elprans** [comment] 2020-01-30 21:06
> It might be useful to add a note somewhere in the docs, as I was assuming that multi link sets could contain duplicates from what it says here that

>> EdgeQL sets are multisets, as they do not require the elements to be unique

In general, yes, but linked sets must be distinct.

@vpetrovykh, please add a clarification to the docs.

**Comment by 1st1** [comment] 2020-05-25 19:23
@elprans Can we fix this for alpha 3? If not please move to alpha 4.

**Comment by elprans** [comment] 2020-05-25 20:48
Moving to a4.

**Comment by msullivan** [comment] 2022-03-02 21:57
This seems fixed

**Closed by msullivan** 2022-03-02 21:57 UTC
Labels: bug, edgeql
