### ISSUE TITLE
Cannot migrate after creating migration schema

### ISSUE THREAD

**Issue by Star3Lord** [edgedb/edgedb#4722] opened 2022-11-28 18:20 UTC
```
edgedb error: InternalServerError: functions in index predicate must be marked IMMUTABLE
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: functions in index predicate must be marked IMMUTABLE
```

- EdgeDB Version: 2.7+5b16920
- EdgeDB CLI Version: 2.2.1+36acd58
- OS Version: official edgedb docker image

Steps to Reproduce:

1. run `edgedb migration create`
2. run `edgedb migrate`

Schema:
```
# using future nonrecursive_access_policies;

module default {
  global current_user_id -> uuid;
  global current_user := (
    select User filter .id = global current_user_id
  );

  abstract type Auditable {
    required property created_at -> datetime {
      readonly := true;
      default := datetime_current();
    };
    required property modified_at -> datetime {
      default := datetime_current();
    };
    link last_modified_by -> User;
  }
  
  abstract type Stateful {
    required property is_active -> bool {
      default := true;
    };
    required property is_deleted -> bool {
      default := false;
    };
    property deleted_at -> datetime;
    link deleted_by -> User;

    constraint expression on (
      not exists .deleted_at if .is_deleted else true
    ) {
      errmessage := 'deleted_at must be set if is_deleted is true';
    };
  }

  type User extending Auditable, Stateful, subscription::SubscriptionTarget {
    required property username -> str {
      # constraint exclusive {
      #   errmessage := 'User with this username already exists';
      # };
      constraint max_len_value(255) {
        errmessage := 'Username must be less than 255 characters';
      };
    };
    required property password_hash -> str;
    required property email -> str {
      constraint max_len_value(255) {
        errmessage := 'Email must be less than 255 characters';
      };
    };
    required property is_verified -> bool {
      default := false;
    };
    required property is_superuser -> bool {
      default := false;
    };
    link profile := .<user[is Profile];
    link dndy_account := .<user[is account::DndyAccount];
    multi link oauth_accounts := .<user[is account::OAuthAccount];
    multi link calendar_events := .<user[is event::CalendarEvent];
    multi link subscriptions := .<subscriber[is subscription::Subscription];
    multi link subscriptions_of := .<target[is subscription::Subscription];

    constraint exclusive on (.email) except (.is_deleted) {
      errmessage := 'User with this email already exists';
    };

    access policy other_users_cannot_change
      deny update, delete
      using ((global current_user_id ?!= .id) or (global current_user.is_superuser ?!= true));
  }

  type Profile extending Auditable, Stateful {
    required property first_name -> str {
      constraint max_len_value(255) {
        errmessage := 'First name must be less than 255 characters';
      };
    };
    required property last_name -> str {
      constraint max_len_value(255) {
        errmessage := 'Last name must be less than 255 characters';
      };
    };
    property full_name := .first_name ++ ' ' ++ .last_name;
    property phone_number -> str {
      constraint max_len_value(20) {
        errmessage := 'Phone number must be less than 20 characters';
      };
    };
    link image -> Image;
    required link user -> User {
        constraint exclusive {
            errmessage := 'User can only have one profile';
        };
    };

    access policy other_users_cannot_change
      deny update, delete
      using ((global current_user_id ?!= .user.id) or (global current_user.is_superuser ?!= true));
  }

  type Image {
    required property url -> str {
      constraint regexp(r'%^(?:(?:(?:https?|ftp):)?\/\/)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z0-9\x{00a1}-\x{ffff}][a-z0-9\x{00a1}-\x{ffff}_-]{0,62})?[a-z0-9\x{00a1}-\x{ffff}]\.)+(?:[a-z\x{00a1}-\x{ffff}]{2,}\.?))(?::\d{2,5})?(?:[/?#]\S*)?$%iuS');
    }
  }
}

module account {
  scalar type AccountType extending enum<Dndy, OAuth>;

  abstract type Account extending default::Auditable, default::Stateful {
    required link user -> default::User;
    required property type -> AccountType;
  }

  scalar type DndyStatus extending enum<`On`, Off>;

  type DndyAccount extending Account {
    annotation title := 'Dndy Account';
    required property status -> DndyStatus {
      default := DndyStatus.Off;
    };

    constraint expression on (
      .type = AccountType.Dndy
    ) {
      errmessage := 'Account type must be Dndy';
    };
    constraint exclusive on ((.user, .type)) except (.is_deleted) {
      errmessage := 'User can only have one Dndy account';
    };
  }

  type OAuthAccount extending Account {
    annotation title := 'OAuth Account';
    required property provider -> str {
      constraint max_len_value(255) {
        errmessage := 'Provider must be less than 255 characters';
      };
    };
    required property external_id -> str {
      constraint max_len_value(255) {
        errmessage := 'Provider ID must be less than 255 characters';
      };
    };
    required property access_token -> str;
    required property refresh_token -> str;
    property id_token -> str;
    property expires_at -> datetime;
    property cache -> str;
    property scopes -> array<str>;

    constraint expression on (
      .type = AccountType.OAuth
    ) {
      errmessage := 'Account type must be OAuth';
    };
    constraint exclusive on ((.user, .type, .provider, .external_id)) except (.is_deleted) {
      errmessage := 'User can only have one OAuth account per provider';
    };
  }
    
}

module event {
  type Event extending default::Auditable, default::Stateful, subscription::SubscriptionTarget {
    required link user -> default::User;
    required property source -> str {
      default := 'internal';
    };
    required property title -> str {
      constraint max_len_value(255) {
        errmessage := 'Event title must be less than 255 characters';
      };
    };
    property description -> str;
    property start_date -> cal::local_date;
    property start_datetime -> cal::local_datetime;
    property start_timezone -> str;
    property end_date -> cal::local_date;
    property end_datetime -> cal::local_datetime;
    property end_timezone -> str;
    property location -> str;

    multi link subscriptions_of := .<target[is subscription::Subscription];

    constraint expression on (
      (exists .start_date or exists .start_datetime)
      and not (exists .start_date and exists .start_datetime)
    ) {
      errmessage := 'Either start_date or start_datetime must be set';
    };

    constraint expression on (
      (exists .end_date or exists .end_datetime)
      and not (exists .end_date and exists .end_datetime)
    ) {
      errmessage := 'Either end_date or end_datetime must be set';
    };
  }

  scalar type CalendarEventType extending enum<`Single`, Recurring, RecurringInstance>;

  type CalendarEvent extending Event {
    required property type -> CalendarEventType {
      default := CalendarEventType.`Single`;
    };
    property show_as -> str;
    property external_id -> str;
    required property is_cancelled -> bool {
      default := false;
    };
    required property is_public -> bool {
      default := false;
    };
    required property is_all_day -> bool {
      default := false;
    };
    property is_recurring := .type = CalendarEventType.Recurring;
    property rrule -> str;
    
    constraint expression on (
      not exists .rrule if .type = CalendarEventType.Recurring else true
    ) {
      errmessage := 'rrule must be set if is_recurring is true';
    };

    # only apply the constraint if the event is recurring instance
    constraint exclusive on (
      (.user, .source, .external_id)
    ) except (
      .is_deleted or .type != CalendarEventType.RecurringInstance or .type != CalendarEventType.Recurring
    ) {
      errmessage := 'User already has an event with this external_id';
    };
  }
}

module notification {
  scalar type NotificationLevel extending enum<Low, Medium, High>;
  scalar type NotificationType extending enum<App, Push, Email, SMS>;

  type Notification extending default::Auditable, default::Stateful {
    required link user -> default::User;
    required property type -> NotificationType {
      default := NotificationType.App;
    };
    required property is_seen -> bool {
      default := false;
    };
    required property initiator -> str {
      default := 'internal';
      constraint max_len_value(255) {
        errmessage := 'Initiator must be less than 255 characters';
      };
    };
    required property title -> str {
      constraint max_len_value(255) {
        errmessage := 'Notification title must be less than 255 characters';
      };
    };
    required property body -> str;
    required property level -> NotificationLevel {
      default := NotificationLevel.Medium;
    };
  }
}


module subscription {
  abstract type SubscriptionTarget {
  }

  scalar type SubscriptionType extending enum<OneTime, Recurring>;

  type Subscription extending default::Auditable, default::Stateful {
    required link subscriber -> default::User;
    link target -> SubscriptionTarget;
    required property type -> SubscriptionType;
    required property is_expired -> bool {
      default := false;
    };
    multi link notifications -> notification::Notification;

    constraint exclusive on ((.subscriber, .target, .type)) except (.is_deleted) {
      errmessage := 'User already has a subscription to this target';
    };
  }
}
```

**Comment by msullivan** [comment] 2022-12-02 00:42
Thanks for the bug report. The issue is in referencing enum literals from indexes/constraints.
You should be able to work around this issue by instead casting the enum value to a string and comparing that.

I'm not sure if we'll fix this properly in 2.x, though we should make it produce an error message that explains where the problem is. I think fixing it requires introducing a new function in the database for each enum, and we don't have the mechanisms to modify the representation of the user's schema as part of minor version upgrades. We could probably detect whether the user has an out-of-date enum that needs to be fixed and give remediation instructions, but I'm not sure if that is worth it.

Closing because this is a duplicate of  #4592.

**Closed by msullivan** 2022-12-02 00:42 UTC
Labels: bug, compiler

**Comment by Star3Lord** [comment] 2022-12-02 01:35
can you show me where to cast?

> Thanks for the bug report. The issue is in referencing enum literals from indexes/constraints. You should be able to work around this issue by instead casting the enum value to a string and comparing that.
> 
> I'm not sure if we'll fix this properly in 2.x, though we should make it produce an error message that explains where the problem is. I think fixing it requires introducing a new function in the database for each enum, and we don't have the mechanisms to modify the representation of the user's schema as part of minor version upgrades. We could probably detect whether the user has an out-of-date enum that needs to be fixed and give remediation instructions, but I'm not sure if that is worth it.
> 
> Closing because this is a duplicate of #4592.

Can you show me how can I do that? I tried casting the field and the Enum literal but didn't work.
