### ISSUE TITLE
Roadmap is very out of date

### ISSUE THREAD

**Issue by jquesada2016** [edgedb/edgedb#6166] opened 2023-09-26 18:36 UTC
- EdgeDB Version: N/A
- EdgeDB CLI Version: N/a
- OS Version: N/A

Steps to Reproduce:

1. Go to https://www.edgedb.com/roadmap
2. Read the outdatedness of most features

Schema: N/A

**Comment by 1st1** [comment] 2023-09-26 18:53
@jaclarke can you kill the page? 😅 We hid it specifically because it's out of date, but probably some sites still link to it.

**Comment by jquesada2016** [comment] 2023-09-26 19:51
Yeah, it's the first search result on Google when searching `edgedb roadmap`.

**Comment by haikyuu** [comment] 2023-09-27 06:20
I think it's a very beautiful page. Why not repurpose it to showcase all (most) the features of EdgeDB?

**Comment by raddevon** [comment] 2023-09-27 11:54
One of the downsides of an accelerated release schedule is that, although we can deliver features much more quickly (every 4 months instead of every year-and-change), it means there's a lot more time devoted to the actual releases (3x the number of releases over a year than before). Three releases take a lot more time than one, even if the one would have had roughly the same number of features because there's an overhead associated with each one.

That means some of the time we could have spent telling you about what's coming _next_ is instead shifted to telling you about what's coming _now_. 😅  I think it's probably the right trade-off to make — delivering features vs. telling you about them — but we're still small enough and busy enough at the moment that it is a trade-off we have to make.

I don't think that will be the case forever though. We have plans to refresh it, but we just can't prioritize it at the moment. Disabling it isn't permanent. It's just that, for now, it's doing more harm than good as people stumble upon it and either calibrate expectations from it or get confused by it. For now, our monthly office hours sessions on Discord can serve as an opportunity for people to get some clarity around future plans until we're able to revamp the roadmap.

**Comment by raddevon** [comment] 2024-02-05 14:08
Good point. I'll close this one as a duplicate of #5097

**Closed by raddevon** 2024-02-05 14:08 UTC
