### ISSUE TITLE
repl implicit limit wrecks user specified limit/offset

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb#7500] opened 2024-06-27 15:04 UTC
![image](https://github.com/edgedb/edgedb/assets/239003/20249636-6ee9-41eb-9a8d-d93409443a3e)

https://discord.com/channels/841451783728529451/849377751370432573/1255641719462953061

**Comment by msullivan** [comment] 2024-06-28 21:41
Duplicate of https://github.com/edgedb/edgedb/issues/3627

**Closed by msullivan** 2024-06-28 21:41 UTC
Labels: compiler
