### ISSUE TITLE
Generated Migration cannot be executed

### ISSUE THREAD

**Issue by brassel** [edgedb/edgedb#4673] opened 2022-11-15 08:56 UTC
# Versions

edgedb --version
EdgeDB CLI 2.1.0+527e309
edgedb instance list
2.6+db69671
on MacOS 12.6 (21G115) 

# Description

Trying to create a default value for a link yields a migration script like this.
~~~
CREATE MIGRATION m17knaxk3azsyvu2nwcvpu7slyo2ivenjoajtuzzrez7k3pkppjkrq
    ONTO m1qs42zq35mdjxwkaai57vmdqz4m2ab2migxux6mmkwntgqnjpddna
{
  ALTER TYPE default::MyType {
      CREATE REQUIRED LINK sub2 -> default::MySubType {
          SET default := (INSERT
              default::MySubType
          );
      };
  };
};
~~~
But trying to execute this script throws the following error.
~~~
edgedb migrate
Connecting to an EdgeDB instance at localhost:10704...
edgedb error: UnsupportedBackendFeatureError: WITH clause containing a data-modifying statement must be at the top level
~~~

# Steps to reproduce

## Step 1
Create a new project and create two linked types by migration to this `default.esdl`.
~~~
module default {
    type MySubType {
        required property name -> std::str {
            default := '';
        };
    };
    type MyType {
        required link sub2 -> default::MySubType {
            default := (insert
                default::MySubType
            );
        };
        property number -> std::int64;
        required property number2 -> std::int64 {
            default := 0;
        };
    };
};
~~~
## Step 2
Then extend the `default.esdl` by a link with a default to create a new sub object for every new parent object.
~~~
module default {
    type MySubType {
        required property name -> std::str {
            default := '';
        };
    };
    type MyType {
        required link sub -> default::MySubType {
            default := (insert
                default::MySubType
            );
        };
        required link sub2 -> default::MySubType {
            default := (insert
                default::MySubType
            );
        };
        property number -> std::int64;
        required property number2 -> std::int64 {
            default := 0;
        };
    };
};
~~~
## Step 3
The command `edgedb migration create` will generate the script which cannot be executed.
~~~
CREATE MIGRATION m17knaxk3azsyvu2nwcvpu7slyo2ivenjoajtuzzrez7k3pkppjkrq
    ONTO m1qs42zq35mdjxwkaai57vmdqz4m2ab2migxux6mmkwntgqnjpddna
{
  ALTER TYPE default::MyType {
      CREATE REQUIRED LINK sub2 -> default::MySubType {
          SET default := (INSERT
              default::MySubType
          );
      };
  };
};
~~~
## Step 4
The command `edgedb migrate` throws the error.
~~~
edgedb migrate
Connecting to an EdgeDB instance at localhost:10704...
edgedb error: UnsupportedBackendFeatureError: WITH clause containing a data-modifying statement must be at the top level
~~~

**Comment by tailhook** [comment] 2022-11-15 15:34
Think looks like an edgedb bug, rather than Rust-specific.

**Comment by msullivan** [comment] 2022-11-15 16:18
Dupe of https://github.com/edgedb/edgedb/issues/4372 / https://github.com/edgedb/edgedb/issues/3592

**Closed** 2022-11-15 16:20 UTC
