### ISSUE TITLE
Error when running a sequence of queries and returning multiple variables

### ISSUE THREAD

**Issue by dotlouis** [edgedb/edgedb#4350] opened 2022-09-13 15:51 UTC
- EdgeDB Version: 2.1+52c90a7
- OS Version: macOS 12.5.1 (M1)

Hi all,

Given a schema that looks like this (simplified for readability):

```GraphQL
module default {
  type Submission {
    required link account -> auth::Account
    required link contact -> default::Contact
  }
  type Contact {
    required link account -> auth::Account
    required link sharedContact -> shared::Contact
    link submission := .<contact[is Submission];
  }
}

module shared {
  type Contact {
    property name -> str;
    multi link accountContacts := .<sharedContact[is default::Contact];
    multi link employments := .<contact[is shared::Employment];
  }

  type Employment {
      required link contact -> shared::Contact;
      required link company -> shared::Company
  }

  type Company {
      property name -> str;
      multi link employments := .<company[is shared::Employment];
  }
}
```

I have this query that uses WITH block to create nested objects once, and reuse them in subsequent queries:

```GraphQL
WITH
  account := (global currentAccount),
  sharedContact := (
    INSERT shared::Contact {
      name := "Colin"
    } 
    UNLESS CONFLICT ON shared::Contact.linkedinUrl
    ELSE (shared::Contact)
  ),
  contact := (
    INSERT default::Contact {
      account := account,
      sharedContact := sharedContact
    }
  ),
  submission := (
    INSERT default::Submission {
      account := account,
      contact := contact,
    }
  ),
  sharedCompany := (
    INSERT shared::Company {
      name := "EdgeDB"
    } 
    UNLESS CONFLICT ON shared::Company.linkedinUrl
    ELSE (shared::Company)
  ),
  sharedEmployment := (
    INSERT shared::Employment {
      contact := sharedContact,
      company := sharedCompany
    } 
    UNLESS CONFLICT ON shared::Employment.email
    ELSE (shared::Employment)
  )
select (submission, sharedEmployment)
```

However, this throws a rather obscure:

`InternalServerError: None`

I initially wanted to return only the submission (from the select)
```
select submission
```

But it throws a `QueryError: unused alias definition: 'sharedEmployment'`

So I've tried returning both to work around it with a tuple:
```
select (submission, sharedEmployment)
```
or with a free object:
```
select {
  submission := submission,
  sharedEmployment := sharedEmployement
}
```
Both of these methods throws: `InternalServerError: None`

There is a similar discussion around how to sequence queries and return only parts of them in the response:
https://github.com/edgedb/edgedb/discussions/3906

Appreciate any recommendation or feedback. Thanks

**Comment by elprans** [comment] 2022-09-13 17:48
Hm. I get a slightly different error:

```
edgedb error: InternalServerError: operator does not exist: text = uuid
```

**Comment by dotlouis** [comment] 2022-09-15 13:07
I definitely don't have this error. Weird. Do you know what line/part of the schema it is referencing?

**Comment by msullivan** [comment] 2022-10-19 22:59
Hey, sorry to take so long to reply and then just ask for more info, but could you please share a complete schema that is sufficient to reproduce the issue?

We've reproduced *an* issue, but possibly not the one you are trying to report!

**Comment by msullivan** [comment] 2022-10-19 23:31
The bug I was hitting (and probably Elvis) came specifically from listing in the `UNLESS CONFLICT` clause a property that is not actually inserted. Fix for that is coming up.

**Comment by msullivan** [comment] 2023-02-10 01:19
I'm closing this because I'm unable to reproduce it, but if you have more information please reopen!

**Closed as not planned by msullivan** 2023-02-10 01:19 UTC
Labels: bug, need info, compiler
