### ISSUE TITLE
edb.errors.InternalServerError while applying migration that changes a scalar Enum type (adding or updating the possible values)

### ISSUE THREAD

**Issue by im-murilo** [edgedb/edgedb#5497] opened 2023-05-17 08:57 UTC
- EdgeDB Version: 2.14+ce9e786
- EdgeDB CLI Version: 2.3.1+5d93f42
- OS Version: macOS Ventura 13.3.1

Steps to Reproduce:

1. Change the possible values of an enum inside default.esdl - Update existing options or add new ones.
2. Create a migration file `edgedb migration create`
3. Execute the migration `edgedb migrate`

Error received:
```
edgedb error: InternalServerError: cannot drop type edgedbpub."fe423448-f48e-11ed-afa0-45eaddf2ad32_domain" because other objects depend on it
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      edb.errors.InternalServerError: cannot drop type edgedbpub."fe423448-f48e-11ed-afa0-45eaddf2ad32_domain" because other objects depend on it
```

Migration file:
```
CREATE MIGRATION m1eg3jqw5eortjz56gnat5zznoetb7s3sxcvzhoi4rh3ovchody32a
    ONTO m1j2yyrohr7dm5ktedpd7fhhgsqo5wlbw64bl5oeat24z4qnqve6fq
{
  ALTER SCALAR TYPE default::ExternalSiteType EXTENDING enum<officialWebsite, officialAgenda, socialMediaProfile, socialMediaPost>;
};
```
Schema:
Originally:
` scalar type ExternalSiteType extending enum<officialWebsite, socialMediaProfile, socialMediaPost>;`
Desired migration:
` scalar type ExternalSiteType extending enum<officialWebsite, officialAgenda, socialMediaProfile, socialMediaPost>;`

**Comment by msullivan** [comment] 2023-05-17 18:07
I'm going to close this issue as a duplicate of the fixed https://github.com/edgedb/edgedb/issues/5365. Please reopen it if I was mistaken!

**Closed by msullivan** 2023-05-17 18:07 UTC
