### ISSUE TITLE
Database breaking randomly

### ISSUE THREAD

**Issue by gsouf** [edgedb/edgedb#1334] opened 2020-04-12 14:18 UTC
- EdgeDB Version: 1.0-alpha.2+g16f75ece5.d20200122 
- OS Version: Running in docker - Host unbuntu 19.10

Steps to Reproduce:

Cannot say, it produced randomly with a database that was working well. The db broke, the js client returned this error:

```
code: 16777216
message: "cannot issue new command"
type: "InternalServerError"
```

Stoping a restarting the docker instance solved the issue.

Please let me know how I can provide more details if it occurs again

**Comment by gsouf** [comment] 2020-04-12 14:39
I believe I found what happens. 

First scalar types breaks graphql. Second, removing the scalar type breaks https interfaces.

Not related to the JS client. As I said in my initial message.

 Here are the steps:

1. create a scalar type:

```
CREATE scalar type FooOrBar extending enum<"foo", "bar">;
```

2. Try to load something via graphql. Graphql is broken after adding this scalar type.

3. Remove the scalar type.

4. Try to load something via graphql or edgeql over http.

**Comment by elprans** [comment] 2020-04-12 15:36
This seems to be a problem specific to HTTP ports: #1314

**Comment by gsouf** [comment] 2020-04-12 18:29
@elprans it happened again today after I ran some mutation on my database. Some of them contained syntax errors.
It's it's related to concurent connexion then it might be because some errors don't have a proper handling and cause connection to remain active (or believed to be active). 

I can run more tests if required.

**Comment by ambv** [comment] 2020-05-31 18:32
Reproduced this as well. Agree with @elvis that this looks like a duplicate of #1314.

**Comment by 1st1** [comment] 2020-06-01 18:25
@ambv Are you looking into this one or should I look at this?

**Comment by ambv** [comment] 2020-06-01 18:28
I didn't do anything here besides reproducing the problem. Feel free to assign to me.

**Comment by 1st1** [comment] 2020-06-01 23:00
> I didn't do anything here besides reproducing the problem. Feel free to assign to me.

It's OK, please take a look tomorrow.

**Closed** 2020-09-25 04:17 UTC
