### ISSUE TITLE
Issue with `query_work_mem`

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#1533] opened 2020-07-13 13:28 UTC
When running non dev mode edgedb, I get the following:
```
edgedb> describe system config;
{
  'CONFIGURE SYSTEM SET listen_port := 5656;
CONFIGURE SYSTEM SET listen_addresses := {};
CONFIGURE SYSTEM SET shared_buffers := \'3234960kB\';
CONFIGURE SYSTEM SET query_work_mem := \'"6144kB"\';   // <-- here is double escaping
CONFIGURE SYSTEM SET effective_cache_size := \'8087392kB\';
CONFIGURE SYSTEM SET effective_io_concurrency := \'1\';
CONFIGURE SYSTEM SET default_statistics_target := \'100\';
',
}
```
This isn't problem with describe config, because this is processed as a string same as other configuration settings around, and `SELECT cfg::get_config_json()` gives the same bug.

But I can't reproduce that by setting a value:
```
edgedb> CONFIGURE SYSTEM SET query_work_mem := '"8192kB"';
Error: ERROR: InvalidValueError: invalid value for parameter "work_mem": ""8192kB""
edgedb> CONFIGURE SYSTEM SET query_work_mem := '16384kB';
OK: CONFIGURE SYSTEM
edgedb> describe system config;
{
  'CONFIGURE SYSTEM SET listen_port := 5656;
CONFIGURE SYSTEM SET listen_addresses := {};
CONFIGURE SYSTEM SET shared_buffers := \'3234960kB\';
CONFIGURE SYSTEM SET query_work_mem := \'16384kB\';
CONFIGURE SYSTEM SET effective_cache_size := \'8087392kB\';
CONFIGURE SYSTEM SET effective_io_concurrency := \'1\';
CONFIGURE SYSTEM SET default_statistics_target := \'100\';
',
}
```
This probably has something to do with settings the value in `bootstrap.py` (other settings set there do not have this problem, though), but I don't understand what is the issue yet.

**Comment by tailhook** [comment] 2020-07-13 14:07
It looks like the only difference of this property is that `cfg::backend_setting` of `query_work_mem` is `work_mem` (i.e. edgedb's name doesn't match postgres name).

**Comment by tailhook** [comment] 2020-07-13 14:15
Hm, the other difference is that `query_work_mem` is not a system setting.

**Comment by elprans** [comment] 2020-08-23 22:33
Fixed in d87b9b347d2d970e79d6648c0c930b87ad1fb66b.

**Comment by tailhook** [comment] 2020-12-16 13:38
This popped up again in alpha7:
```
 edgedb error: error applying init file "./tmp/dump_02/init.edgeql": failed statement "CONFIGURE SYSTEM SET effective_cache_size := \'\"3560646kB\"\';": ERROR: InvalidValueError: invalid value for parameter "effective_cache_size": ""3560646kB""
 ```
 https://github.com/edgedb/edgedb-cli/runs/1563760999?check_suite_focus=true#step:5:724
 
 It's harder to reproduce locally, as crashes only in non-devmode.

**Comment by elprans** [comment] 2020-12-16 17:55
Hm. I can't reproduce locally.  I forced the code branch that configures the `query_work_mem` paramter and both `DESCRIBE SYSTEM CONFIG` and `edgedb dump --all` generate correct description for me.  Which version is producing the dump in that test?

**Comment by tailhook** [comment] 2020-12-16 18:23
Whatever is installed by `edgedb-setup`. `edgedb-server-1-alpha7_1.0a7-2020121204~bionic_amd64.deb` in this case.

**Comment by tailhook** [comment] 2020-12-16 18:33
Can reproduce the issue locally, having this error:
```
edgedb error: error applying init file "./tmp/dump_02/init.edgeql": failed statement "CONFIGURE SYSTEM SET effective_cache_size := \'\"8087386kB\"\';": ERROR:
InvalidValueError: invalid value for parameter "effective_cache_size": ""8087386kB""
```
Which is kinda the same, just settings are perhaps reordered. I can also confirm that alpha6 doesn't have this bug.

**Comment by tailhook** [comment] 2020-12-18 14:57
```
> edgedb server install
> edgedb server init test1
> edgedb -Itest1 query 'describe system config'
"CONFIGURE SYSTEM SET shared_buffers := '408680kB';CONFIGURE SYSTEM SET query_work_mem := '\"6144kB\"';CONFIGURE SYSTEM SET effective_cache_size := '1021702kB';"
```
reproduces the issue.

But I'm not sure why the issues is seen in `query_work_mem` but not in `effective_cache_size` in this case.

Also note that output doesn't include newlines anymore (which isn't a big issue, but isn't nice).

**Comment by tailhook** [comment] 2020-12-25 15:07
This still fails my tests in CLI. But now consistently with `effective_cache_size` error (https://github.com/edgedb/edgedb-cli/pull/212/checks?check_run_id=1608579556#step:5:732). @elprans, did you fix something related to `query_work_mem`, or this is just a coincidence?

**Comment by elprans** [comment] 2020-12-25 16:39
I didn't touch anything yet.  Will try to repro locally soon.

**Comment by elprans** [comment] 2021-01-12 18:53
#2116 should stop the bug from surfacing in default installs.  I'm looking at the underlying issue now.

**Closed** 2021-01-13 02:38 UTC
Labels: bug
