### ISSUE TITLE
Trailing comma is invalid syntax for calling functions

### ISSUE THREAD

**Issue by Fogapod** [edgedb/edgedb#1636] opened 2020-08-05 17:02 UTC
- EdgeDB Version: `1.0-alpha.4+dev.110.gc569d8dc`
- OS Version: Docker

Steps to Reproduce:

```edgeql
CREATE FUNCTION test(a: int64) -> int64 { USING ( SELECT a ) };
SELECT test(
  1,
)
# error: Unexpected ')'
```

In python this is a valid syntax:
```python
test(
  1,
)
test (1,)
```
And this is not:
```python
test(,)
```

Current behavior is inconsistent, trailing commas are allowed in `SELECT`, `INSERT`, etc.

**Comment by elprans** [comment] 2020-08-05 17:06
Dupe of #1462?

**Comment by Fogapod** [comment] 2020-08-05 17:08
Sorry, didn't notice that issue

**Closed** 2020-08-23 22:39 UTC
Labels: bug
