### ISSUE TITLE
Bad error reporting when changing schema

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb#968] opened 2019-12-14 16:05 UTC
Initial schema is kinda:
```
module default {
    type Ticket {
        required property title -> str;
    }
}
```
And the new schema is:
```
module default {
    abstract type Something {
        property kind -> str;
    }
    type Ticket extending Something {
        required property title -> str;
    }
}
```
I'm not sure if this update makes sense, but the error definitely don't:
```
InternalServerError: 'kind'
```

**Comment by elprans** [comment] 2019-12-14 17:59
The migration is valid. This is a bug. @vpetrovykh, please take a look.

**Comment by Fogapod** [comment] 2020-02-01 14:15
@vpetrovykh what's the status on this issue?
I can't migrate my project and continue working with edgedb because of it. Is there a workaround with DDL maybe? I'm not sure what's going on here.

**Comment by elprans** [comment] 2020-02-01 17:55
I can reproduce.  Will have a fix soon.

**Comment by elprans** [comment] 2020-02-01 18:07
@Fogapod Meanwhile, here's how you can workaround with DDL (assuming your case from #1147):

```
START TRANSACTION;
CREATE ABSTRACT TYPE Editable;
ALTER TYPE User EXTENDING Editable;
ALTER TYPE Article EXTENDING Editable;
ALTER TYPE Editable {
    CREATE REQUIRED PROPERTY created_at -> datetime {
        SET default := datetime_current();
        SET readonly := true;
    };
    CREATE PROPERTY edited_at -> datetime;
};
COMMIT;
```

**Comment by 1st1** [comment] 2020-02-12 00:10
@vpetrovykh I think this was fixed recently, wasn't it?

**Comment by elprans** [comment] 2020-02-12 00:20
@1st1 No, this isn't fixed, and the fix is quite hairy.  This will be fixed once the migration backend rewrite is done.

**Comment by 1st1** [comment] 2020-05-25 19:38
@elprans I assume this is A4 material?

**Comment by elprans** [comment] 2020-05-25 20:57
Yes, a4.

**Comment by elprans** [comment] 2020-09-29 19:18
This ix fixed.

**Closed by elprans** 2020-09-29 19:18 UTC
Labels: bug, migrations, sql
