### ISSUE TITLE
Unable to 'create-migration',  edb.common.topological.CycleError

### ISSUE THREAD

**Issue by Maffels** [edgedb/edgedb#2399] opened 2021-03-24 15:50 UTC
- EdgeDB Version: 1.0-beta.1+g2eee1afe4.d2021030
- OS Version: Windows 10, running EdgeDB in docker

While working through the new EdgeDB asyncio tutorial; calling "edgedb -Icommonplace create-migration" returns an error. 
It happens when I try to migrate from an earlier scheme to the final one as seen in the commonplace github repository.
It furthermore tells me this is probably a bug with EdgeDB and that I should report it. 

```
Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 312, in worker
          res = meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 198, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 2004, in compile_in_tx
          return self._compile(ctx=ctx, source=source), ctx.state
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1545, in _compile
          return self._try_compile(ctx=ctx, source=original)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1602, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1484, in _compile_dispatch_ql
          query = self._compile_ql_migration(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1001, in _compile_ql_migration
          guided_diff = s_ddl.delta_schemas(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/schema/ddl.py", line 331, in delta_schemas
          objects = s_ordering.linearize_delta(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/schema/ordering.py", line 110, in linearize_delta
          sortedlist = [i[1] for i in topological.sort_ex(depgraph)]
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 176, in sort_ex
          visit(key)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 159, in visit
          visit(n, weak_link=weak_link)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 159, in visit
          visit(n, weak_link=weak_link)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 159, in visit
          visit(n, weak_link=weak_link)
        [Previous line repeated 1 more time]
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 139, in visit
          raise CycleError(
      edb.common.topological.CycleError: dependency cycle between ('rebase', 'commonplace::__|idx@commonplace|User@9d90cf377a2f853658647aee44bf0af75bcc1e3a@name') and ('rebase', 'commonplace::__|idx@commonplace|User@9d90cf377a2f853658647aee44bf0af75bcc1e3a@name')
```

Kind regards and my apologies in advance if I missed something obvious.

**Comment by elprans** [comment] 2021-03-24 18:24
> It happens when I try to migrate from an earlier scheme

Are you able to provide the text of that earlier schema?

**Comment by Maffels** [comment] 2021-03-24 18:46
the first schema which was used in the original migration was the following: 
`module commonplace {
    type User {
        required property name -> str;
    };
};
`
This then got updated to 

`module commonplace {
    type User {
        required property name -> str {
            constraint exclusive;
        };
        index on (__subject__.name);
    };
};`
Trying to migrate to the end scheme results in the error posted above.

**Comment by elprans** [comment] 2021-03-24 20:00
Looks like this is caused by a combination of rebasing onto a new mixin and a conversion of a `str` property to `Slug`.  Here's a minimal repro:

```
rollback;
start transaction;
start migration to {
  module commonplace {
    type User {
      required property name -> str;
      index on (__subject__.name);
    };
  };
};
populate migration;
commit migration;
start migration to {
  module commonplace {
    scalar type Slug extending str;
    abstract type Named {
      required property name -> Slug;
      index on (__subject__.name);
    };
    type User extending Named;
  };
};
populate migration;
commit migration;
rollback;
```

**Comment by Maffels** [comment] 2021-03-24 20:08
The 3rd last command again gives me a CycleError:
When putting in `populate migration;` I get: 

```
ERROR: InternalServerError: dependency cycle between ('rebase', 'commonplace::__|idx@commonplace|User@9d90cf377a2f853658647aee44bf0af75bcc1e3a@name') and ('rebase', 'commonplace::__|idx@commonplace|User@9d90cf377a2f853658647aee44bf0af75bcc1e3a@name')
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 312, in worker
          res = meth(*args)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler_pool/worker.py", line 198, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 2004, in compile_in_tx
          return self._compile(ctx=ctx, source=source), ctx.state
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1545, in _compile
          return self._try_compile(ctx=ctx, source=original)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1602, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(ctx, stmt)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 1484, in _compile_dispatch_ql
          query = self._compile_ql_migration(ctx, ql)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/server/compiler/compiler.py", line 931, in _compile_ql_migration
          diff = s_ddl.delta_schemas(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/schema/ddl.py", line 331, in delta_schemas
          objects = s_ordering.linearize_delta(
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/schema/ordering.py", line 110, in linearize_delta
          sortedlist = [i[1] for i in topological.sort_ex(depgraph)]
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 176, in sort_ex
          visit(key)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 159, in visit
          visit(n, weak_link=weak_link)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 159, in visit
          visit(n, weak_link=weak_link)
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 159, in visit
          visit(n, weak_link=weak_link)
        [Previous line repeated 1 more time]
        File "/usr/lib/x86_64-linux-gnu/edgedb-server-1-beta1/lib/python3.9/site-packages/edb/common/topological.py", line 139, in visit
          raise CycleError(
      edb.common.topological.CycleError: dependency cycle between ('rebase', 'commonplace::__|idx@commonplace|User@9d90cf377a2f853658647aee44bf0af75bcc1e3a@name') and ('rebase', 'commonplace::__|idx@commonplace|User@9d90cf377a2f853658647aee44bf0af75bcc1e3a@name')
edgedb[tx:failed]>
```

**Comment by msullivan** [comment] 2021-03-27 00:38
I think this one might be tricky, and there is a lot going on here.
1. We are inferring that `name` should be dropped. Maybe we want to tweak the compcoef of is_owned so that we don't think it is a drop by default, though it would be OK if we can reject the suggestion.
2. We are complaining about a cycle. This is because we have deletes depend on the rebase of their referrers, so the delete of the prop depends on the rebase of the index. The rebase of the index depends on the *creation* of the new prop, which depends on the deletion of the prop, which brings us to a cycle. I made deletes depend on rebases of their referrers in https://github.com/edgedb/edgedb/pull/2024/, to handle cases where doing the rebase would eliminate the reference, but maybe something smarter needs to be done. (To only do it in cases where the rebase actually accomplishes that?)
3. If we are going to try to generate `DROP PROPERTY name`, I think we also need to drop the index. I don't know if we have any sort of mechanism for ensuring this sort of thing stays in sync? We also need to make sure that the DROP gets sorted before the rebase, which it doesn't now, but that's an easy fix I think.
4. If we are going to try to generate something that preserves the property data (which we should I think), then we need to generate a SET TYPE that goes before the rebase to make the types match up before the rebase can happen. I think this might require drawing some more distinctions in ordering, since I think normally we try to put changes *after* a rebase.

**Comment by msullivan** [comment] 2021-11-02 19:14
Part 2 of the breakdown above has been fixed. Parts 3 and 4 are still open.
Part 1 is a bit of a question mark, we might not want to do it. Some issues that prevented the suggestion of deleting the property from being rejected have been fixed, but that just results into running into part 4.

(Breaking the migration into a couple parts can solve the problems here, though.)

**Comment by msullivan** [comment] 2021-11-02 20:43
I'm closing this in favor of #3118 and #3119.

**Closed by msullivan** 2021-11-02 20:43 UTC
Labels: bug, migrations
