### ISSUE TITLE
"InternalServerError: reference to an undefined item" for no reason

### ISSUE THREAD

**Issue by divan** [edgedb/edgedb#5247] opened 2023-03-24 04:48 UTC
So I was removing the type from the schema and forgot that it's referenced by another type. (I deleted the .esdl file and run `edgedb migration create`)

On migrate I got this exception with stracktrace:

```
edgedb error: InternalServerError: reference to an undefined item rules::Rule in rules::Disciplinerule@segments
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 160, in compile
          units, cstate = COMPILER.compile(
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2282, in compile
          unit_group = self._compile(ctx=ctx, source=source)
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1812, in _compile
          return self._try_compile(ctx=ctx, source=source)
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1876, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1734, in _compile_dispatch_ql
          query = self._compile_ql_migration(
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1093, in _compile_ql_migration
          target_schema = s_ddl.apply_sdl(
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/schema/ddl.py", line 426, in apply_sdl
          ddl_stmts = s_decl.sdl_to_ddl(current_schema, documents)
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/edgeql/declarative.py", line 428, in sdl_to_ddl
          ordered = topological.sort(ddlgraph, allow_unresolved=False)
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/common/topological.py", line 197, in sort
          items = sort_ex(graph, allow_unresolved=allow_unresolved)
        File "/Users/divan/Library/Application Support/edgedb/portable/2.12/lib/python3.10/site-packages/edb/common/topological.py", line 121, in sort_ex
          raise UnresolvedReferenceError(
      edb.common.topological.UnresolvedReferenceError: reference to an undefined item rules::Rule in rules::Disciplinerule@segments
make: [migrate] Error 1 (ignored)
```

Upon closer inspection turned out that, sure, I need to rename/remove the reference from another type. So that case looks like a normal error, not the exception with internal server error.

Probably should just show an error message saying that removed type is still referenced?

**Comment by efaust** [comment] 2023-05-31 19:59
Duplicate of (now closed) #5559

**Closed** 2023-05-31 19:59 UTC
Labels: bug, compiler
