### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Mulugruntz** [edgedb/edgedb#1264] opened 2020-02-25 19:16 UTC
I'm trying to find a way to add bulks of items into the db (something like the `COPY` postgres https://www.postgresql.org/docs/current/sql-copy.html would be perfect).

When I add 3 items, it works. When I add 100 it fails.
When I add 1000, it fails... with a slightly different error message! (`InternalServerError: maximum recursion depth exceeded`). The `while calling a Python object` part is missing.

- EdgeDB Version: 1 alpha 2
- OS Version: docker image

Steps to Reproduce:

1.  ```INSERT Index { name := 'idx1' };```
2.
```sql
WITH idx1 := (SELECT Index FILTER Index.name = 'idx1'),
FOR x IN {
    (<datetime>'2014-10-31T00:02:41+00', 9145.5),
    (<datetime>'2014-10-31T00:02:53+00', 9145.5),
    (<datetime>'2014-10-31T00:02:59+00', 9146.6),
    (<datetime>'2014-10-31T00:03:42+00', 9145.5),
    (<datetime>'2014-10-31T00:03:58+00', 9146.6),
    (<datetime>'2014-10-31T00:04:02+00', 9145.5),
    (<datetime>'2014-10-31T00:04:06+00', 9146.6),
    (<datetime>'2014-10-31T00:04:08+00', 9146.1),
    (<datetime>'2014-10-31T00:04:11+00', 9146.6),
    (<datetime>'2014-10-31T00:05:21+00', 9145.5),
    (<datetime>'2014-10-31T00:09:14+00', 9146.1),
    (<datetime>'2014-10-31T00:09:39+00', 9146.1),
    (<datetime>'2014-10-31T00:09:55+00', 9146.6),
    (<datetime>'2014-10-31T00:10:28+00', 9145.5),
    (<datetime>'2014-10-31T00:12:28+00', 9146.1),
    (<datetime>'2014-10-31T00:12:34+00', 9146.6),
    (<datetime>'2014-10-31T00:12:41+00', 9145.5),
    (<datetime>'2014-10-31T00:14:15+00', 9146.1),
    (<datetime>'2014-10-31T00:14:25+00', 9146.6),
    (<datetime>'2014-10-31T00:15:20+00', 9146.1),
    (<datetime>'2014-10-31T00:15:23+00', 9145.5),
    (<datetime>'2014-10-31T00:15:24+00', 9146.1),
    (<datetime>'2014-10-31T00:15:41+00', 9146.6),
    (<datetime>'2014-10-31T00:15:48+00', 9146.1),
    (<datetime>'2014-10-31T00:15:58+00', 9146.6),
    (<datetime>'2014-10-31T00:16:00+00', 9145.5),
    (<datetime>'2014-10-31T00:16:01+00', 9145.5),
    (<datetime>'2014-10-31T00:16:02+00', 9145.5),
    (<datetime>'2014-10-31T00:16:03+00', 9145.5),
    (<datetime>'2014-10-31T00:16:04+00', 9146.1),
    (<datetime>'2014-10-31T00:16:05+00', 9145.5),
    (<datetime>'2014-10-31T00:16:06+00', 9145.5),
    (<datetime>'2014-10-31T00:16:07+00', 9145.5),
    (<datetime>'2014-10-31T00:16:08+00', 9145.5),
    (<datetime>'2014-10-31T00:16:09+00', 9145.5),
    (<datetime>'2014-10-31T00:16:10+00', 9145.5),
    (<datetime>'2014-10-31T00:16:11+00', 9145.5),
    (<datetime>'2014-10-31T00:16:12+00', 9145.5),
    (<datetime>'2014-10-31T00:16:13+00', 9145.5),
    (<datetime>'2014-10-31T00:16:14+00', 9145.5),
    (<datetime>'2014-10-31T00:16:15+00', 9145.5),
    (<datetime>'2014-10-31T00:16:16+00', 9145.5),
    (<datetime>'2014-10-31T00:16:17+00', 9145.5),
    (<datetime>'2014-10-31T00:16:18+00', 9145.5),
    (<datetime>'2014-10-31T00:16:19+00', 9145.5),
    (<datetime>'2014-10-31T00:16:20+00', 9145.5),
    (<datetime>'2014-10-31T00:16:21+00', 9145.5),
    (<datetime>'2014-10-31T00:16:22+00', 9145.5),
    (<datetime>'2014-10-31T00:16:23+00', 9145.5),
    (<datetime>'2014-10-31T00:16:24+00', 9145.5),
    (<datetime>'2014-10-31T00:16:25+00', 9145.5),
    (<datetime>'2014-10-31T00:16:26+00', 9145.5),
    (<datetime>'2014-10-31T00:16:27+00', 9145.5),
    (<datetime>'2014-10-31T00:16:28+00', 9145.5),
    (<datetime>'2014-10-31T00:16:29+00', 9145.5),
    (<datetime>'2014-10-31T00:16:30+00', 9145.5),
    (<datetime>'2014-10-31T00:16:31+00', 9145.5),
    (<datetime>'2014-10-31T00:16:32+00', 9145.5),
    (<datetime>'2014-10-31T00:16:33+00', 9145.5),
    (<datetime>'2014-10-31T00:16:34+00', 9145.5),
    (<datetime>'2014-10-31T00:16:35+00', 9145.5),
    (<datetime>'2014-10-31T00:16:36+00', 9145.5),
    (<datetime>'2014-10-31T00:16:37+00', 9145.5),
    (<datetime>'2014-10-31T00:16:38+00', 9145.5),
    (<datetime>'2014-10-31T00:16:39+00', 9145.5),
    (<datetime>'2014-10-31T00:16:40+00', 9145.5),
    (<datetime>'2014-10-31T00:16:41+00', 9145.5),
    (<datetime>'2014-10-31T00:16:42+00', 9145.5),
    (<datetime>'2014-10-31T00:16:43+00', 9145.5),
    (<datetime>'2014-10-31T00:16:44+00', 9145.5),
    (<datetime>'2014-10-31T00:16:45+00', 9145.5),
    (<datetime>'2014-10-31T00:16:46+00', 9145.5),
    (<datetime>'2014-10-31T00:16:47+00', 9145.5),
    (<datetime>'2014-10-31T00:16:48+00', 9145.5),
    (<datetime>'2014-10-31T00:16:49+00', 9145.5),
    (<datetime>'2014-10-31T00:16:50+00', 9145.5),
    (<datetime>'2014-10-31T00:16:51+00', 9145.5),
    (<datetime>'2014-10-31T00:16:52+00', 9145.5),
    (<datetime>'2014-10-31T00:16:53+00', 9145.5),
    (<datetime>'2014-10-31T00:16:54+00', 9145.5),
    (<datetime>'2014-10-31T00:16:55+00', 9145.5),
    (<datetime>'2014-10-31T00:16:56+00', 9145.5),
    (<datetime>'2014-10-31T00:16:57+00', 9145.5),
    (<datetime>'2014-10-31T00:16:58+00', 9145.5),
    (<datetime>'2014-10-31T00:16:59+00', 9145.5),
    (<datetime>'2014-10-31T00:28:18+00', 9144.5),
    (<datetime>'2014-10-31T00:28:50+00', 9144.5),
    (<datetime>'2014-10-31T00:38:07+00', 9145.5),
    (<datetime>'2014-10-31T00:38:19+00', 9145.5),
    (<datetime>'2014-10-31T00:38:38+00', 9146.6),
    (<datetime>'2014-10-31T00:38:39+00', 9145.5),
    (<datetime>'2014-10-31T00:38:41+00', 9146.1),
    (<datetime>'2014-10-31T00:38:46+00', 9146.6),
    (<datetime>'2014-10-31T00:38:47+00', 9145.5),
    (<datetime>'2014-10-31T00:38:53+00', 9146.6),
    (<datetime>'2014-10-31T00:38:55+00', 9145.5),
    (<datetime>'2014-10-31T00:40:16+00', 9146.6),
    (<datetime>'2014-10-31T00:44:15+00', 9146.1),
    (<datetime>'2014-10-31T00:44:25+00', 9146.6),
    (<datetime>'2014-10-31T00:45:09+00', 9147.6),
}
UNION (INSERT History {
    index := idx1,
    timestamp := x.0,
    value := x.1
});
```

Schema:
```sql
module default {
    type Index {
        required property name -> str {
            constraint exclusive;
        }
    }

    type History {
        required link index -> Index;
        required property timestamp -> datetime;
        required property value -> float64;
    }
}
```

Result:
```console
InternalServerError: maximum recursion depth exceeded while calling a Python object
Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md  
```

**Comment by elprans** [comment] 2020-02-25 19:29
This is a duplicate of #475.  You don't have to generate a huge EdgeQL query like this, pass the data as an array, and use `array_unpack`:

```
WITH idx1 := (SELECT Index FILTER Index.name = 'idx1'),
FOR x IN {
    array_unpack(<tuple<datetime, float64>>$data)
}
UNION (INSERT History {
    index := idx1,
    timestamp := x.0,
    value := x.1
});
```

**Closed by elprans** 2020-02-25 19:29 UTC

**Comment by Mulugruntz** [comment] 2020-02-25 20:13
Thanks @elprans !

However, I seem to have another bug...
I give this to the data
```python
data = [(datetime.datetime(2014, 10, 31, 0, 2, 41, tzinfo=datetime.timezone.utc), 9145.5), (datetime.datetime(2014, 10, 31, 0, 2, 53, tzinfo=datetime.timezone.utc), 9145.5), (datetime.datetime(2014, 10, 31, 0, 2, 59, tzinfo=datetime.timezone.utc), 9146.6), (datetime.datetime(2014, 10, 31, 0, 3, 42, tzinfo=datetime.timezone.utc), 9145.5), (datetime.datetime(2014, 10, 31, 0, 3, 58, tzinfo=datetime.timezone.utc), 9146.6)]

query = """
WITH idx1 := (SELECT Index FILTER Index.name = 'idx1'),
FOR x IN {
    array_unpack(<tuple<datetime, float64>>$data)
}
UNION (INSERT History {
    index := idx1,
    timestamp := x.0,
    value := x.1
});
"""

async with connection.transaction():
    await connection.fetchall(query, data=data)
```

And this gives me
```console
edgedb.errors.QueryError: cannot pass tuples as query parameters
```

What am I doing wrong?

**Comment by elprans** [comment] 2020-02-25 20:33
Ah, right. Tuples as arguments are currently unsupported (this is a Postgres restriction really). So, one way to implement this is to use JSON as input instead:

```
WITH idx1 := (SELECT Index FILTER Index.name = 'idx1'),
FOR x IN {json_array_unpack(<json>$json_array)}
UNION (
UNION (INSERT History {
    index := idx1,
    timestamp := <datetime>x[0],
    value := <float64>x[1]
});
```

Where `$json_array` is the result of `json.dumps()`.  In this scenario you need to make sure your `datetime` data is a proper ISO-formatted string that includes the timezone.

**Comment by Mulugruntz** [comment] 2020-02-25 21:18
Thanks @elprans !

It took 56 seconds to insert 73,247 records. Using containers.
I'll do more tests tomorrow :).

Time to sleep (past 5am, in HK) thanks for your support!

**Comment by elprans** [comment] 2020-02-25 21:58
> 56 seconds to insert 73,247 records

This seems a bit slow (considering the query above).  Did you include the time to `json.dumps()` the dataset?

**Comment by Mulugruntz** [comment] 2020-02-26 07:15
Yeah, I also found it rather slow.
Nope, the dump is not included in the time.
This is exactly my code:
```python
json_batch_values = ujson.dumps(batch_values)
start_sub = datetime.now()
await connection.fetchall(ddl, data=json_batch_values)
logger.info(f"DDL query {i}/{n_sub_queries} completed in {(datetime.now() - start_sub).total_seconds()} secs!")
```
with `ddl` being a string containing the version of the query from your previous post.

**Comment by Mulugruntz** [comment] 2020-02-26 07:49
@elprans , I destroyed the containers and the volumes, recreated everything and did this a couple times and now it's:

- 21.8 sec.
- 20.1 sec.
- 17.5 sec.
- 17.0 sec.
- 18.4 sec.

If that gives an idea (with a brand new empty DB). I'm running docker on a late 2016 MBP (13").
