### ISSUE TITLE
Inserts in a migration are significantly slower than outside a migration

### ISSUE THREAD

**Issue by MicroDroid** [edgedb/edgedb#5713] opened 2023-06-28 17:10 UTC
- EdgeDB Version: 2.12+4727bd2
- EdgeDB CLI Version: EdgeDB CLI 2.3.1+a3f40f2
- OS Version: Arch Linux inside WSL

Just do a bunch (1k+) of inserts in migration and watch it takes minutes to finish.

**Comment by msullivan** [comment] 2023-06-29 23:45
Shared with me on discord, https://github.com/MicroDroid/edgedb-slow-migration-repro/blob/main/dbschema/migrations/00002.edgeql is a migration script that breaks.

I'm pretty sure the problem is that compiling all those inserts is just slow, but if you run them against the server normally, they will probably hit the query compiler cache.

It /might/ be possible for us to do normalization/caching *within* migration scripts, though it would be pretty hairy and would only benefit this particular use-case of "doing a thousand of a identical (modulo constants) insert".

If you want to populate a lot of objects in a migration, I think the fastest way would be to define them all in a big json literal and use that to do a bulk insert, like:
```
with data := to_json('[
  {
    "code": "717aca3c-1369-483d-bcf7-e82c460e0f54",
    "prop1": "20246dab-e3c1-4475-82d8-66bcb8c96104",
    "prop2": "b4e80a66-662e-4ff6-9090-32e8bca02fa0",
    "prop3": "a3924104-43b1-4f6b-8b05-c2812fc0e8c1"
  },
  {
    "code": "ea9e8555-2ac6-4883-a3d7-b4882e6f8cf3",
    "prop1": "25da0d63-d713-478c-a862-46fe4bce700f",
    "prop2": "99378e04-63e7-4448-8e82-ca980253ded7",
    "prop3": "ccc6e3cf-2697-4f49-8f79-7eb56971c9e5"
  }
]')
for el in <tuple<code: str, prop1: str, prop2: str, prop3: str>>json_array_unpack(data) union (
  insert Car { code := el.code, prop1 := el.prop1, prop2 := el.prop2, prop3 := el.prop3, }
);
```

**Comment by MicroDroid** [comment] 2023-06-30 05:45
Oh, got it. Makes sense.

I guess I should close this issue then? Cause it doesn't sound like worth more investigation/fixing

**Comment by msullivan** [comment] 2023-10-19 01:15
Yeah I'll close it

**Closed by msullivan** 2023-10-19 01:15 UTC
Labels: performance, server, compiler
