### ISSUE TITLE
Docker edgedb/edgedb:latest isn't latest

### ISSUE THREAD

**Issue by midzdotdev** [edgedb/edgedb#4901] opened 2023-01-18 22:57 UTC
Hey guys, I think something's up with CI or Docker tags and I don't believe this would be intentional.

`edgedb/edgedb:2` was uploaded `Dec 16, 2022 at 6:13 pm`.
`edgedb/edgedb:2.9` is references the same image.

`edgedb/edgedb:latest` was uploaded `Nov 19, 2022 at 3:40 am`.

I noticed when the `:latest` image wouldn't allow the `/server/status/alive` health check but did allow `/server/status/ready`.
FWIW, I can confirm both of these health checks are present in `:2` and `:2.9`.

**Comment by midzdotdev** [comment] 2023-01-18 23:07
If I had to take a guess, it would be something to do with this logic.

https://github.com/edgedb/edgedb/blob/a73a40d88dc9bc226509318f87d7f574abde74c8/.github/workflows/release.yml#L2265-L2267

**Comment by midzdotdev** [comment] 2023-01-18 23:13
Just realised I'm in the wrong repo, I'll repost there.

**Comment by elprans** [comment] 2023-01-18 23:18
That's because we pushed 3.0-alpha.1 and that made `2.x` not "the latest".  Need to adjust that bit to ignore prereleases.  Also this is the correct place., since the issue is in the workflow in this repo.

**Comment by elprans** [comment] 2023-01-18 23:19
Meanwhile, I just manually pushed ":latest".

**Comment by midzdotdev** [comment] 2023-01-18 23:31
That was a lightning fast response!

Thought something was up with my docker cache, but just pruned and run the specific sha with
```sh
docker run --rm -it -p 5656:5656 -e EDGEDB_SERVER_SECURITY=insecure_dev_mode edgedb/edgedb@sha256:e78b55b8dcf1ff26b51d6c1bc0ae5d9d484761fb3349241711c23df7e305391f
```

Seems like `curl http://localhost:5656/server/status/alive` still gives `Unknown path`...

Also there is only `linux/amd64` pushed as `:latest`, not the `arm` one 🚨.

**Comment by elprans** [comment] 2023-01-19 00:28
> Seems like `curl http://localhost:5656/server/status/alive` still gives `Unknown path`...

Should be `curl -k https://127.0.0.1:5656/server/status/alive`
 
> Also there is only `linux/amd64` pushed as `:latest`, not the `arm` one rotating_light.

Fixed now.

**Closed** 2023-01-19 18:32 UTC
