### ISSUE TITLE
Problems using a symbol defined in a WITH block in SDL.

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb#2320] opened 2021-03-05 17:53 UTC
- EdgeDB Version: 1.0.0-beta.1
- OS Version: Linux

Steps to Reproduce:

The following schema fails to create a migration:
```
module default {
    type Foo {
        property val -> str;
        property comp := count((
            WITH x := .val
            SELECT y := Bar FILTER x = y.val
        ))
    }

    type Bar {
        property val -> str;
    }
};
```
The error message is:
```
ERROR: InvalidReferenceError: schema item 'std::x' does not exist
edgedb error: cannot proceed until .esdl files are fixed
```

It appears that validation during tracing is at fault.

**Comment by elprans** [comment] 2021-03-05 17:55
Seems to be a duplicate of #1452

**Closed** 2021-03-12 19:27 UTC
Labels: bug, migrations
